"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file

This program source code file is part of KiCad, a free EDA CAD application.

Copyright (C) 2024 KiCad Developers, see AUTHORS.txt for contributors.

This program is free software: you can redistribute it and/or modify it
under the terms of the GNU General Public License as published by the
Free Software Foundation, either version 3 of the License, or (at your
option) any later version.

This program is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License along
with this program.  If not, see <http://www.gnu.org/licenses/>.
"""
import builtins
import collections.abc
from .. import common
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
from .. import schematic
import typing
DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class GetSchematicHierarchy(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    DOCUMENT_FIELD_NUMBER: builtins.int

    @property
    def document(self) -> common.types.base_types_pb2.DocumentSpecifier:
        """Type must be DT_SCHEMATIC and only the project is considered"""

    def __init__(self, *, document: common.types.base_types_pb2.DocumentSpecifier | None=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['document', b'document']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['document', b'document']) -> None:
        ...
global___GetSchematicHierarchy = GetSchematicHierarchy

@typing.final
class SchematicHierarchyResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    DOCUMENT_FIELD_NUMBER: builtins.int
    TOP_LEVEL_SHEETS_FIELD_NUMBER: builtins.int

    @property
    def document(self) -> common.types.base_types_pb2.DocumentSpecifier:
        ...

    @property
    def top_level_sheets(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[schematic.schematic_types_pb2.SheetInstance]:
        ...

    def __init__(self, *, document: common.types.base_types_pb2.DocumentSpecifier | None=..., top_level_sheets: collections.abc.Iterable[schematic.schematic_types_pb2.SheetInstance] | None=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['document', b'document']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['document', b'document', 'top_level_sheets', b'top_level_sheets']) -> None:
        ...
global___SchematicHierarchyResponse = SchematicHierarchyResponse

@typing.final
class GetSchematicNetlist(google.protobuf.message.Message):
    """Returns SchematicNetlistResponse"""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    DOCUMENT_FIELD_NUMBER: builtins.int
    TYPES_FIELD_NUMBER: builtins.int

    @property
    def document(self) -> common.types.base_types_pb2.DocumentSpecifier:
        """Type must be DT_SCHEMATIC and only the project is considered"""

    @property
    def types(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[common.types.enums_pb2.KiCadObjectType.ValueType]:
        """Optional filter for types of items to return in SchematicNetSheetContents items fields.
        If not specified, all types will be returned.  Only connectable schematic items are valid
        here (pins, labels, wires, etc).
        """

    def __init__(self, *, document: common.types.base_types_pb2.DocumentSpecifier | None=..., types: collections.abc.Iterable[common.types.enums_pb2.KiCadObjectType.ValueType] | None=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['document', b'document']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['document', b'document', 'types', b'types']) -> None:
        ...
global___GetSchematicNetlist = GetSchematicNetlist

@typing.final
class SchematicNetlistResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    DOCUMENT_FIELD_NUMBER: builtins.int
    NETS_FIELD_NUMBER: builtins.int

    @property
    def document(self) -> common.types.base_types_pb2.DocumentSpecifier:
        ...

    @property
    def nets(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[schematic.schematic_types_pb2.SchematicNet]:
        ...

    def __init__(self, *, document: common.types.base_types_pb2.DocumentSpecifier | None=..., nets: collections.abc.Iterable[schematic.schematic_types_pb2.SchematicNet] | None=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['document', b'document']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['document', b'document', 'nets', b'nets']) -> None:
        ...
global___SchematicNetlistResponse = SchematicNetlistResponse