"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file

This program source code file is part of KiCad, a free EDA CAD application.

Copyright The KiCad Developers, see AUTHORS.txt for contributors.
@author Jon Evans <jon@craftyjon.com>

This program is free software: you can redistribute it and/or modify it
under the terms of the GNU General Public License as published by the
Free Software Foundation, either version 3 of the License, or (at your
option) any later version.

This program is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License along
with this program.  If not, see <http://www.gnu.org/licenses/>.
"""
import builtins
import collections.abc
from .. import common
import google.protobuf.any_pb2
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing
if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions
DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _SchematicLineType:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _SchematicLineTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_SchematicLineType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    SLT_UNKNOWN: _SchematicLineType.ValueType
    SLT_WIRE: _SchematicLineType.ValueType
    SLT_BUS: _SchematicLineType.ValueType
    SLT_GRAPHIC: _SchematicLineType.ValueType

class SchematicLineType(_SchematicLineType, metaclass=_SchematicLineTypeEnumTypeWrapper):
    ...
SLT_UNKNOWN: SchematicLineType.ValueType
SLT_WIRE: SchematicLineType.ValueType
SLT_BUS: SchematicLineType.ValueType
SLT_GRAPHIC: SchematicLineType.ValueType
global___SchematicLineType = SchematicLineType

class _BusEntryType:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _BusEntryTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_BusEntryType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    BET_UNKNOWN: _BusEntryType.ValueType
    BET_WIRE_TO_BUS: _BusEntryType.ValueType
    BET_BUS_TO_BUS: _BusEntryType.ValueType

class BusEntryType(_BusEntryType, metaclass=_BusEntryTypeEnumTypeWrapper):
    ...
BET_UNKNOWN: BusEntryType.ValueType
BET_WIRE_TO_BUS: BusEntryType.ValueType
BET_BUS_TO_BUS: BusEntryType.ValueType
global___BusEntryType = BusEntryType

class _SchematicLabelShape:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _SchematicLabelShapeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_SchematicLabelShape.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    SLSH_UNKNOWN: _SchematicLabelShape.ValueType
    SLSH_INPUT: _SchematicLabelShape.ValueType
    SLSH_OUTPUT: _SchematicLabelShape.ValueType
    SLSH_BIDI: _SchematicLabelShape.ValueType
    SLSH_TRISTATE: _SchematicLabelShape.ValueType
    SLSH_PASSIVE: _SchematicLabelShape.ValueType
    SLSH_DOT: _SchematicLabelShape.ValueType
    SLSH_CIRCLE: _SchematicLabelShape.ValueType
    SLSH_DIAMOND: _SchematicLabelShape.ValueType
    SLSH_RECTANGLE: _SchematicLabelShape.ValueType

class SchematicLabelShape(_SchematicLabelShape, metaclass=_SchematicLabelShapeEnumTypeWrapper):
    ...
SLSH_UNKNOWN: SchematicLabelShape.ValueType
SLSH_INPUT: SchematicLabelShape.ValueType
SLSH_OUTPUT: SchematicLabelShape.ValueType
SLSH_BIDI: SchematicLabelShape.ValueType
SLSH_TRISTATE: SchematicLabelShape.ValueType
SLSH_PASSIVE: SchematicLabelShape.ValueType
SLSH_DOT: SchematicLabelShape.ValueType
SLSH_CIRCLE: SchematicLabelShape.ValueType
SLSH_DIAMOND: SchematicLabelShape.ValueType
SLSH_RECTANGLE: SchematicLabelShape.ValueType
global___SchematicLabelShape = SchematicLabelShape

class _SchematicLabelSpinStyle:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _SchematicLabelSpinStyleEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_SchematicLabelSpinStyle.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    SLSS_UNKNOWN: _SchematicLabelSpinStyle.ValueType
    SLSS_LEFT: _SchematicLabelSpinStyle.ValueType
    SLSS_UP: _SchematicLabelSpinStyle.ValueType
    SLSS_RIGHT: _SchematicLabelSpinStyle.ValueType
    SLSS_BOTTOM: _SchematicLabelSpinStyle.ValueType

class SchematicLabelSpinStyle(_SchematicLabelSpinStyle, metaclass=_SchematicLabelSpinStyleEnumTypeWrapper):
    ...
SLSS_UNKNOWN: SchematicLabelSpinStyle.ValueType
SLSS_LEFT: SchematicLabelSpinStyle.ValueType
SLSS_UP: SchematicLabelSpinStyle.ValueType
SLSS_RIGHT: SchematicLabelSpinStyle.ValueType
SLSS_BOTTOM: SchematicLabelSpinStyle.ValueType
global___SchematicLabelSpinStyle = SchematicLabelSpinStyle

class _SheetSide:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _SheetSideEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_SheetSide.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    SHS_UNKNOWN: _SheetSide.ValueType
    SHS_LEFT: _SheetSide.ValueType
    SHS_RIGHT: _SheetSide.ValueType
    SHS_TOP: _SheetSide.ValueType
    SHS_BOTTOM: _SheetSide.ValueType

class SheetSide(_SheetSide, metaclass=_SheetSideEnumTypeWrapper):
    ...
SHS_UNKNOWN: SheetSide.ValueType
SHS_LEFT: SheetSide.ValueType
SHS_RIGHT: SheetSide.ValueType
SHS_TOP: SheetSide.ValueType
SHS_BOTTOM: SheetSide.ValueType
global___SheetSide = SheetSide

class _SchematicSymbolType:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _SchematicSymbolTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_SchematicSymbolType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    SST_UNKNOWN: _SchematicSymbolType.ValueType
    SST_NORMAL: _SchematicSymbolType.ValueType
    SST_GLOBAL_POWER: _SchematicSymbolType.ValueType
    SST_LOCAL_POWER: _SchematicSymbolType.ValueType

class SchematicSymbolType(_SchematicSymbolType, metaclass=_SchematicSymbolTypeEnumTypeWrapper):
    ...
SST_UNKNOWN: SchematicSymbolType.ValueType
SST_NORMAL: SchematicSymbolType.ValueType
SST_GLOBAL_POWER: SchematicSymbolType.ValueType
SST_LOCAL_POWER: SchematicSymbolType.ValueType
global___SchematicSymbolType = SchematicSymbolType

class _SchematicSymbolOrientation:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _SchematicSymbolOrientationEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_SchematicSymbolOrientation.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    SSO_UNKNOWN: _SchematicSymbolOrientation.ValueType
    SSO_0: _SchematicSymbolOrientation.ValueType
    SSO_90: _SchematicSymbolOrientation.ValueType
    SSO_180: _SchematicSymbolOrientation.ValueType
    SSO_270: _SchematicSymbolOrientation.ValueType

class SchematicSymbolOrientation(_SchematicSymbolOrientation, metaclass=_SchematicSymbolOrientationEnumTypeWrapper):
    ...
SSO_UNKNOWN: SchematicSymbolOrientation.ValueType
SSO_0: SchematicSymbolOrientation.ValueType
SSO_90: SchematicSymbolOrientation.ValueType
SSO_180: SchematicSymbolOrientation.ValueType
SSO_270: SchematicSymbolOrientation.ValueType
global___SchematicSymbolOrientation = SchematicSymbolOrientation

class _SchematicPinOrientation:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _SchematicPinOrientationEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_SchematicPinOrientation.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    SPO_UNKNOWN: _SchematicPinOrientation.ValueType
    SPO_RIGHT: _SchematicPinOrientation.ValueType
    SPO_LEFT: _SchematicPinOrientation.ValueType
    SPO_UP: _SchematicPinOrientation.ValueType
    SPO_DOWN: _SchematicPinOrientation.ValueType

class SchematicPinOrientation(_SchematicPinOrientation, metaclass=_SchematicPinOrientationEnumTypeWrapper):
    ...
SPO_UNKNOWN: SchematicPinOrientation.ValueType
SPO_RIGHT: SchematicPinOrientation.ValueType
SPO_LEFT: SchematicPinOrientation.ValueType
SPO_UP: SchematicPinOrientation.ValueType
SPO_DOWN: SchematicPinOrientation.ValueType
global___SchematicPinOrientation = SchematicPinOrientation

class _SchematicPinShape:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _SchematicPinShapeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_SchematicPinShape.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    SPS_UNKNOWN: _SchematicPinShape.ValueType
    SPS_LINE: _SchematicPinShape.ValueType
    SPS_INVERTED: _SchematicPinShape.ValueType
    SPS_CLOCK: _SchematicPinShape.ValueType
    SPS_INVERTED_CLOCK: _SchematicPinShape.ValueType
    SPS_INPUT_LOW: _SchematicPinShape.ValueType
    SPS_CLOCK_LOW: _SchematicPinShape.ValueType
    SPS_OUTPUT_LOW: _SchematicPinShape.ValueType
    SPS_FALLING_EDGE_CLOCK: _SchematicPinShape.ValueType
    SPS_NONLOGIC: _SchematicPinShape.ValueType

class SchematicPinShape(_SchematicPinShape, metaclass=_SchematicPinShapeEnumTypeWrapper):
    ...
SPS_UNKNOWN: SchematicPinShape.ValueType
SPS_LINE: SchematicPinShape.ValueType
SPS_INVERTED: SchematicPinShape.ValueType
SPS_CLOCK: SchematicPinShape.ValueType
SPS_INVERTED_CLOCK: SchematicPinShape.ValueType
SPS_INPUT_LOW: SchematicPinShape.ValueType
SPS_CLOCK_LOW: SchematicPinShape.ValueType
SPS_OUTPUT_LOW: SchematicPinShape.ValueType
SPS_FALLING_EDGE_CLOCK: SchematicPinShape.ValueType
SPS_NONLOGIC: SchematicPinShape.ValueType
global___SchematicPinShape = SchematicPinShape

@typing.final
class SchematicField(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    NAME_FIELD_NUMBER: builtins.int
    TEXT_FIELD_NUMBER: builtins.int
    VISIBLE_FIELD_NUMBER: builtins.int
    SHOW_NAME_FIELD_NUMBER: builtins.int
    ALLOW_AUTO_PLACE_FIELD_NUMBER: builtins.int
    IS_PRIVATE_FIELD_NUMBER: builtins.int
    name: builtins.str
    'Fields do not currently track a unique ID; but may in the future\n    kiapi.common.types.KIID id = 1;\n    '
    visible: builtins.bool
    show_name: builtins.bool
    allow_auto_place: builtins.bool
    is_private: builtins.bool

    @property
    def text(self) -> common.types.base_types_pb2.Text:
        ...

    def __init__(self, *, name: builtins.str=..., text: common.types.base_types_pb2.Text | None=..., visible: builtins.bool=..., show_name: builtins.bool=..., allow_auto_place: builtins.bool=..., is_private: builtins.bool=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['text', b'text']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['allow_auto_place', b'allow_auto_place', 'is_private', b'is_private', 'name', b'name', 'show_name', b'show_name', 'text', b'text', 'visible', b'visible']) -> None:
        ...
global___SchematicField = SchematicField

@typing.final
class SchematicLine(google.protobuf.message.Message):
    """/ Represents a schematic line segment, which may be a wire, bus, or graphical line"""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ID_FIELD_NUMBER: builtins.int
    START_FIELD_NUMBER: builtins.int
    END_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    STROKE_FIELD_NUMBER: builtins.int
    LOCKED_FIELD_NUMBER: builtins.int
    type: global___SchematicLineType.ValueType
    locked: common.types.base_types_pb2.LockedState.ValueType

    @property
    def id(self) -> common.types.base_types_pb2.KIID:
        ...

    @property
    def start(self) -> common.types.base_types_pb2.Vector2:
        ...

    @property
    def end(self) -> common.types.base_types_pb2.Vector2:
        ...

    @property
    def stroke(self) -> common.types.base_types_pb2.StrokeAttributes:
        ...

    def __init__(self, *, id: common.types.base_types_pb2.KIID | None=..., start: common.types.base_types_pb2.Vector2 | None=..., end: common.types.base_types_pb2.Vector2 | None=..., type: global___SchematicLineType.ValueType=..., stroke: common.types.base_types_pb2.StrokeAttributes | None=..., locked: common.types.base_types_pb2.LockedState.ValueType=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['end', b'end', 'id', b'id', 'start', b'start', 'stroke', b'stroke']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['end', b'end', 'id', b'id', 'locked', b'locked', 'start', b'start', 'stroke', b'stroke', 'type', b'type']) -> None:
        ...
global___SchematicLine = SchematicLine

@typing.final
class Junction(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ID_FIELD_NUMBER: builtins.int
    POSITION_FIELD_NUMBER: builtins.int
    DIAMETER_FIELD_NUMBER: builtins.int
    COLOR_FIELD_NUMBER: builtins.int
    LOCKED_FIELD_NUMBER: builtins.int
    locked: common.types.base_types_pb2.LockedState.ValueType

    @property
    def id(self) -> common.types.base_types_pb2.KIID:
        ...

    @property
    def position(self) -> common.types.base_types_pb2.Vector2:
        ...

    @property
    def diameter(self) -> common.types.base_types_pb2.Distance:
        ...

    @property
    def color(self) -> common.types.base_types_pb2.Color:
        ...

    def __init__(self, *, id: common.types.base_types_pb2.KIID | None=..., position: common.types.base_types_pb2.Vector2 | None=..., diameter: common.types.base_types_pb2.Distance | None=..., color: common.types.base_types_pb2.Color | None=..., locked: common.types.base_types_pb2.LockedState.ValueType=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['color', b'color', 'diameter', b'diameter', 'id', b'id', 'position', b'position']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['color', b'color', 'diameter', b'diameter', 'id', b'id', 'locked', b'locked', 'position', b'position']) -> None:
        ...
global___Junction = Junction

@typing.final
class NoConnectMarker(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ID_FIELD_NUMBER: builtins.int
    POSITION_FIELD_NUMBER: builtins.int
    SIZE_FIELD_NUMBER: builtins.int
    LOCKED_FIELD_NUMBER: builtins.int
    locked: common.types.base_types_pb2.LockedState.ValueType

    @property
    def id(self) -> common.types.base_types_pb2.KIID:
        ...

    @property
    def position(self) -> common.types.base_types_pb2.Vector2:
        ...

    @property
    def size(self) -> common.types.base_types_pb2.Distance:
        ...

    def __init__(self, *, id: common.types.base_types_pb2.KIID | None=..., position: common.types.base_types_pb2.Vector2 | None=..., size: common.types.base_types_pb2.Distance | None=..., locked: common.types.base_types_pb2.LockedState.ValueType=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['id', b'id', 'position', b'position', 'size', b'size']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['id', b'id', 'locked', b'locked', 'position', b'position', 'size', b'size']) -> None:
        ...
global___NoConnectMarker = NoConnectMarker

@typing.final
class BusEntry(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ID_FIELD_NUMBER: builtins.int
    POSITION_FIELD_NUMBER: builtins.int
    SIZE_FIELD_NUMBER: builtins.int
    STROKE_FIELD_NUMBER: builtins.int
    LOCKED_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    locked: common.types.base_types_pb2.LockedState.ValueType
    type: global___BusEntryType.ValueType

    @property
    def id(self) -> common.types.base_types_pb2.KIID:
        ...

    @property
    def position(self) -> common.types.base_types_pb2.Vector2:
        ...

    @property
    def size(self) -> common.types.base_types_pb2.Vector2:
        ...

    @property
    def stroke(self) -> common.types.base_types_pb2.StrokeAttributes:
        ...

    def __init__(self, *, id: common.types.base_types_pb2.KIID | None=..., position: common.types.base_types_pb2.Vector2 | None=..., size: common.types.base_types_pb2.Vector2 | None=..., stroke: common.types.base_types_pb2.StrokeAttributes | None=..., locked: common.types.base_types_pb2.LockedState.ValueType=..., type: global___BusEntryType.ValueType=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['id', b'id', 'position', b'position', 'size', b'size', 'stroke', b'stroke']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['id', b'id', 'locked', b'locked', 'position', b'position', 'size', b'size', 'stroke', b'stroke', 'type', b'type']) -> None:
        ...
global___BusEntry = BusEntry

@typing.final
class SchematicText(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ID_FIELD_NUMBER: builtins.int
    TEXT_FIELD_NUMBER: builtins.int
    LOCKED_FIELD_NUMBER: builtins.int
    EXCLUDE_FROM_SIM_FIELD_NUMBER: builtins.int
    locked: common.types.base_types_pb2.LockedState.ValueType
    exclude_from_sim: builtins.bool

    @property
    def id(self) -> common.types.base_types_pb2.KIID:
        ...

    @property
    def text(self) -> common.types.base_types_pb2.Text:
        ...

    def __init__(self, *, id: common.types.base_types_pb2.KIID | None=..., text: common.types.base_types_pb2.Text | None=..., locked: common.types.base_types_pb2.LockedState.ValueType=..., exclude_from_sim: builtins.bool=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['id', b'id', 'text', b'text']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['exclude_from_sim', b'exclude_from_sim', 'id', b'id', 'locked', b'locked', 'text', b'text']) -> None:
        ...
global___SchematicText = SchematicText

@typing.final
class SchematicTextBox(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ID_FIELD_NUMBER: builtins.int
    TEXTBOX_FIELD_NUMBER: builtins.int
    GRAPHIC_ATTRIBUTES_FIELD_NUMBER: builtins.int
    LOCKED_FIELD_NUMBER: builtins.int
    EXCLUDE_FROM_SIM_FIELD_NUMBER: builtins.int
    MARGIN_LEFT_FIELD_NUMBER: builtins.int
    MARGIN_TOP_FIELD_NUMBER: builtins.int
    MARGIN_RIGHT_FIELD_NUMBER: builtins.int
    MARGIN_BOTTOM_FIELD_NUMBER: builtins.int
    locked: common.types.base_types_pb2.LockedState.ValueType
    exclude_from_sim: builtins.bool

    @property
    def id(self) -> common.types.base_types_pb2.KIID:
        ...

    @property
    def textbox(self) -> common.types.base_types_pb2.TextBox:
        ...

    @property
    def graphic_attributes(self) -> common.types.base_types_pb2.GraphicAttributes:
        ...

    @property
    def margin_left(self) -> common.types.base_types_pb2.Distance:
        ...

    @property
    def margin_top(self) -> common.types.base_types_pb2.Distance:
        ...

    @property
    def margin_right(self) -> common.types.base_types_pb2.Distance:
        ...

    @property
    def margin_bottom(self) -> common.types.base_types_pb2.Distance:
        ...

    def __init__(self, *, id: common.types.base_types_pb2.KIID | None=..., textbox: common.types.base_types_pb2.TextBox | None=..., graphic_attributes: common.types.base_types_pb2.GraphicAttributes | None=..., locked: common.types.base_types_pb2.LockedState.ValueType=..., exclude_from_sim: builtins.bool=..., margin_left: common.types.base_types_pb2.Distance | None=..., margin_top: common.types.base_types_pb2.Distance | None=..., margin_right: common.types.base_types_pb2.Distance | None=..., margin_bottom: common.types.base_types_pb2.Distance | None=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['graphic_attributes', b'graphic_attributes', 'id', b'id', 'margin_bottom', b'margin_bottom', 'margin_left', b'margin_left', 'margin_right', b'margin_right', 'margin_top', b'margin_top', 'textbox', b'textbox']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['exclude_from_sim', b'exclude_from_sim', 'graphic_attributes', b'graphic_attributes', 'id', b'id', 'locked', b'locked', 'margin_bottom', b'margin_bottom', 'margin_left', b'margin_left', 'margin_right', b'margin_right', 'margin_top', b'margin_top', 'textbox', b'textbox']) -> None:
        ...
global___SchematicTextBox = SchematicTextBox

@typing.final
class SchematicGraphicShape(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    SHAPE_FIELD_NUMBER: builtins.int
    ID_FIELD_NUMBER: builtins.int
    LOCKED_FIELD_NUMBER: builtins.int
    locked: common.types.base_types_pb2.LockedState.ValueType

    @property
    def shape(self) -> common.types.base_types_pb2.GraphicShape:
        ...

    @property
    def id(self) -> common.types.base_types_pb2.KIID:
        ...

    def __init__(self, *, shape: common.types.base_types_pb2.GraphicShape | None=..., id: common.types.base_types_pb2.KIID | None=..., locked: common.types.base_types_pb2.LockedState.ValueType=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['id', b'id', 'shape', b'shape']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['id', b'id', 'locked', b'locked', 'shape', b'shape']) -> None:
        ...
global___SchematicGraphicShape = SchematicGraphicShape

@typing.final
class SchematicImage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ID_FIELD_NUMBER: builtins.int
    POSITION_FIELD_NUMBER: builtins.int
    TRANSFORM_ORIGIN_OFFSET_FIELD_NUMBER: builtins.int
    IMAGE_SCALE_FIELD_NUMBER: builtins.int
    IMAGE_DATA_FIELD_NUMBER: builtins.int
    LOCKED_FIELD_NUMBER: builtins.int
    image_data: builtins.bytes
    locked: common.types.base_types_pb2.LockedState.ValueType

    @property
    def id(self) -> common.types.base_types_pb2.KIID:
        ...

    @property
    def position(self) -> common.types.base_types_pb2.Vector2:
        ...

    @property
    def transform_origin_offset(self) -> common.types.base_types_pb2.Vector2:
        ...

    @property
    def image_scale(self) -> common.types.base_types_pb2.Ratio:
        ...

    def __init__(self, *, id: common.types.base_types_pb2.KIID | None=..., position: common.types.base_types_pb2.Vector2 | None=..., transform_origin_offset: common.types.base_types_pb2.Vector2 | None=..., image_scale: common.types.base_types_pb2.Ratio | None=..., image_data: builtins.bytes=..., locked: common.types.base_types_pb2.LockedState.ValueType=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['id', b'id', 'image_scale', b'image_scale', 'position', b'position', 'transform_origin_offset', b'transform_origin_offset']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['id', b'id', 'image_data', b'image_data', 'image_scale', b'image_scale', 'locked', b'locked', 'position', b'position', 'transform_origin_offset', b'transform_origin_offset']) -> None:
        ...
global___SchematicImage = SchematicImage

@typing.final
class LocalLabel(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ID_FIELD_NUMBER: builtins.int
    POSITION_FIELD_NUMBER: builtins.int
    TEXT_FIELD_NUMBER: builtins.int
    SPIN_STYLE_FIELD_NUMBER: builtins.int
    FIELDS_FIELD_NUMBER: builtins.int
    LOCKED_FIELD_NUMBER: builtins.int
    spin_style: global___SchematicLabelSpinStyle.ValueType
    locked: common.types.base_types_pb2.LockedState.ValueType

    @property
    def id(self) -> common.types.base_types_pb2.KIID:
        ...

    @property
    def position(self) -> common.types.base_types_pb2.Vector2:
        ...

    @property
    def text(self) -> common.types.base_types_pb2.Text:
        ...

    @property
    def fields(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___SchematicField]:
        ...

    def __init__(self, *, id: common.types.base_types_pb2.KIID | None=..., position: common.types.base_types_pb2.Vector2 | None=..., text: common.types.base_types_pb2.Text | None=..., spin_style: global___SchematicLabelSpinStyle.ValueType=..., fields: collections.abc.Iterable[global___SchematicField] | None=..., locked: common.types.base_types_pb2.LockedState.ValueType=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['id', b'id', 'position', b'position', 'text', b'text']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['fields', b'fields', 'id', b'id', 'locked', b'locked', 'position', b'position', 'spin_style', b'spin_style', 'text', b'text']) -> None:
        ...
global___LocalLabel = LocalLabel

@typing.final
class GlobalLabel(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ID_FIELD_NUMBER: builtins.int
    POSITION_FIELD_NUMBER: builtins.int
    TEXT_FIELD_NUMBER: builtins.int
    SPIN_STYLE_FIELD_NUMBER: builtins.int
    SHAPE_FIELD_NUMBER: builtins.int
    FIELDS_FIELD_NUMBER: builtins.int
    LOCKED_FIELD_NUMBER: builtins.int
    INTERSHEET_REFS_FIELD_FIELD_NUMBER: builtins.int
    spin_style: global___SchematicLabelSpinStyle.ValueType
    shape: global___SchematicLabelShape.ValueType
    locked: common.types.base_types_pb2.LockedState.ValueType

    @property
    def id(self) -> common.types.base_types_pb2.KIID:
        ...

    @property
    def position(self) -> common.types.base_types_pb2.Vector2:
        ...

    @property
    def text(self) -> common.types.base_types_pb2.Text:
        ...

    @property
    def fields(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___SchematicField]:
        ...

    @property
    def intersheet_refs_field(self) -> global___SchematicField:
        ...

    def __init__(self, *, id: common.types.base_types_pb2.KIID | None=..., position: common.types.base_types_pb2.Vector2 | None=..., text: common.types.base_types_pb2.Text | None=..., spin_style: global___SchematicLabelSpinStyle.ValueType=..., shape: global___SchematicLabelShape.ValueType=..., fields: collections.abc.Iterable[global___SchematicField] | None=..., locked: common.types.base_types_pb2.LockedState.ValueType=..., intersheet_refs_field: global___SchematicField | None=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['id', b'id', 'intersheet_refs_field', b'intersheet_refs_field', 'position', b'position', 'text', b'text']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['fields', b'fields', 'id', b'id', 'intersheet_refs_field', b'intersheet_refs_field', 'locked', b'locked', 'position', b'position', 'shape', b'shape', 'spin_style', b'spin_style', 'text', b'text']) -> None:
        ...
global___GlobalLabel = GlobalLabel

@typing.final
class HierarchicalLabel(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ID_FIELD_NUMBER: builtins.int
    POSITION_FIELD_NUMBER: builtins.int
    TEXT_FIELD_NUMBER: builtins.int
    SPIN_STYLE_FIELD_NUMBER: builtins.int
    SHAPE_FIELD_NUMBER: builtins.int
    FIELDS_FIELD_NUMBER: builtins.int
    LOCKED_FIELD_NUMBER: builtins.int
    spin_style: global___SchematicLabelSpinStyle.ValueType
    shape: global___SchematicLabelShape.ValueType
    locked: common.types.base_types_pb2.LockedState.ValueType

    @property
    def id(self) -> common.types.base_types_pb2.KIID:
        ...

    @property
    def position(self) -> common.types.base_types_pb2.Vector2:
        ...

    @property
    def text(self) -> common.types.base_types_pb2.Text:
        ...

    @property
    def fields(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___SchematicField]:
        ...

    def __init__(self, *, id: common.types.base_types_pb2.KIID | None=..., position: common.types.base_types_pb2.Vector2 | None=..., text: common.types.base_types_pb2.Text | None=..., spin_style: global___SchematicLabelSpinStyle.ValueType=..., shape: global___SchematicLabelShape.ValueType=..., fields: collections.abc.Iterable[global___SchematicField] | None=..., locked: common.types.base_types_pb2.LockedState.ValueType=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['id', b'id', 'position', b'position', 'text', b'text']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['fields', b'fields', 'id', b'id', 'locked', b'locked', 'position', b'position', 'shape', b'shape', 'spin_style', b'spin_style', 'text', b'text']) -> None:
        ...
global___HierarchicalLabel = HierarchicalLabel

@typing.final
class DirectiveLabel(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ID_FIELD_NUMBER: builtins.int
    POSITION_FIELD_NUMBER: builtins.int
    TEXT_FIELD_NUMBER: builtins.int
    SPIN_STYLE_FIELD_NUMBER: builtins.int
    SHAPE_FIELD_NUMBER: builtins.int
    FIELDS_FIELD_NUMBER: builtins.int
    LOCKED_FIELD_NUMBER: builtins.int
    PIN_LENGTH_FIELD_NUMBER: builtins.int
    SYMBOL_SIZE_FIELD_NUMBER: builtins.int
    spin_style: global___SchematicLabelSpinStyle.ValueType
    shape: global___SchematicLabelShape.ValueType
    locked: common.types.base_types_pb2.LockedState.ValueType

    @property
    def id(self) -> common.types.base_types_pb2.KIID:
        ...

    @property
    def position(self) -> common.types.base_types_pb2.Vector2:
        ...

    @property
    def text(self) -> common.types.base_types_pb2.Text:
        ...

    @property
    def fields(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___SchematicField]:
        ...

    @property
    def pin_length(self) -> common.types.base_types_pb2.Distance:
        ...

    @property
    def symbol_size(self) -> common.types.base_types_pb2.Distance:
        ...

    def __init__(self, *, id: common.types.base_types_pb2.KIID | None=..., position: common.types.base_types_pb2.Vector2 | None=..., text: common.types.base_types_pb2.Text | None=..., spin_style: global___SchematicLabelSpinStyle.ValueType=..., shape: global___SchematicLabelShape.ValueType=..., fields: collections.abc.Iterable[global___SchematicField] | None=..., locked: common.types.base_types_pb2.LockedState.ValueType=..., pin_length: common.types.base_types_pb2.Distance | None=..., symbol_size: common.types.base_types_pb2.Distance | None=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['id', b'id', 'pin_length', b'pin_length', 'position', b'position', 'symbol_size', b'symbol_size', 'text', b'text']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['fields', b'fields', 'id', b'id', 'locked', b'locked', 'pin_length', b'pin_length', 'position', b'position', 'shape', b'shape', 'spin_style', b'spin_style', 'symbol_size', b'symbol_size', 'text', b'text']) -> None:
        ...
global___DirectiveLabel = DirectiveLabel

@typing.final
class Group(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ID_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    ITEMS_FIELD_NUMBER: builtins.int
    LOCKED_FIELD_NUMBER: builtins.int
    name: builtins.str
    locked: common.types.base_types_pb2.LockedState.ValueType

    @property
    def id(self) -> common.types.base_types_pb2.KIID:
        ...

    @property
    def items(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[common.types.base_types_pb2.KIID]:
        ...

    def __init__(self, *, id: common.types.base_types_pb2.KIID | None=..., name: builtins.str=..., items: collections.abc.Iterable[common.types.base_types_pb2.KIID] | None=..., locked: common.types.base_types_pb2.LockedState.ValueType=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['id', b'id']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['id', b'id', 'items', b'items', 'locked', b'locked', 'name', b'name']) -> None:
        ...
global___Group = Group

@typing.final
class SheetPin(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ID_FIELD_NUMBER: builtins.int
    POSITION_FIELD_NUMBER: builtins.int
    TEXT_FIELD_NUMBER: builtins.int
    SPIN_STYLE_FIELD_NUMBER: builtins.int
    SHAPE_FIELD_NUMBER: builtins.int
    SIDE_FIELD_NUMBER: builtins.int
    LOCKED_FIELD_NUMBER: builtins.int
    spin_style: global___SchematicLabelSpinStyle.ValueType
    shape: global___SchematicLabelShape.ValueType
    side: global___SheetSide.ValueType
    locked: common.types.base_types_pb2.LockedState.ValueType

    @property
    def id(self) -> common.types.base_types_pb2.KIID:
        ...

    @property
    def position(self) -> common.types.base_types_pb2.Vector2:
        ...

    @property
    def text(self) -> common.types.base_types_pb2.Text:
        ...

    def __init__(self, *, id: common.types.base_types_pb2.KIID | None=..., position: common.types.base_types_pb2.Vector2 | None=..., text: common.types.base_types_pb2.Text | None=..., spin_style: global___SchematicLabelSpinStyle.ValueType=..., shape: global___SchematicLabelShape.ValueType=..., side: global___SheetSide.ValueType=..., locked: common.types.base_types_pb2.LockedState.ValueType=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['id', b'id', 'position', b'position', 'text', b'text']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['id', b'id', 'locked', b'locked', 'position', b'position', 'shape', b'shape', 'side', b'side', 'spin_style', b'spin_style', 'text', b'text']) -> None:
        ...
global___SheetPin = SheetPin

@typing.final
class SheetSymbol(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ID_FIELD_NUMBER: builtins.int
    POSITION_FIELD_NUMBER: builtins.int
    SIZE_FIELD_NUMBER: builtins.int
    BORDER_STROKE_FIELD_NUMBER: builtins.int
    FILL_FIELD_NUMBER: builtins.int
    LOCKED_FIELD_NUMBER: builtins.int
    NAME_FIELD_FIELD_NUMBER: builtins.int
    FILENAME_FIELD_FIELD_NUMBER: builtins.int
    USER_FIELDS_FIELD_NUMBER: builtins.int
    PINS_FIELD_NUMBER: builtins.int
    EXCLUDE_FROM_SIM_FIELD_NUMBER: builtins.int
    EXCLUDE_FROM_BOM_FIELD_NUMBER: builtins.int
    EXCLUDE_FROM_BOARD_FIELD_NUMBER: builtins.int
    DNP_FIELD_NUMBER: builtins.int
    PATH_FIELD_NUMBER: builtins.int
    PAGE_NUMBER_FIELD_NUMBER: builtins.int
    locked: common.types.base_types_pb2.LockedState.ValueType
    exclude_from_sim: builtins.bool
    exclude_from_bom: builtins.bool
    exclude_from_board: builtins.bool
    dnp: builtins.bool
    page_number: builtins.str
    "Page numbers in KiCad are arbitrary user data and don't have to be numeric"

    @property
    def id(self) -> common.types.base_types_pb2.KIID:
        ...

    @property
    def position(self) -> common.types.base_types_pb2.Vector2:
        ...

    @property
    def size(self) -> common.types.base_types_pb2.Vector2:
        ...

    @property
    def border_stroke(self) -> common.types.base_types_pb2.StrokeAttributes:
        ...

    @property
    def fill(self) -> common.types.base_types_pb2.GraphicFillAttributes:
        ...

    @property
    def name_field(self) -> global___SchematicField:
        ...

    @property
    def filename_field(self) -> global___SchematicField:
        ...

    @property
    def user_fields(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___SchematicField]:
        ...

    @property
    def pins(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___SheetPin]:
        ...

    @property
    def path(self) -> common.types.base_types_pb2.SheetPath:
        """For existing sheets, gives the path to the subsheet instance.  Leave blank for new sheets."""

    def __init__(self, *, id: common.types.base_types_pb2.KIID | None=..., position: common.types.base_types_pb2.Vector2 | None=..., size: common.types.base_types_pb2.Vector2 | None=..., border_stroke: common.types.base_types_pb2.StrokeAttributes | None=..., fill: common.types.base_types_pb2.GraphicFillAttributes | None=..., locked: common.types.base_types_pb2.LockedState.ValueType=..., name_field: global___SchematicField | None=..., filename_field: global___SchematicField | None=..., user_fields: collections.abc.Iterable[global___SchematicField] | None=..., pins: collections.abc.Iterable[global___SheetPin] | None=..., exclude_from_sim: builtins.bool=..., exclude_from_bom: builtins.bool=..., exclude_from_board: builtins.bool=..., dnp: builtins.bool=..., path: common.types.base_types_pb2.SheetPath | None=..., page_number: builtins.str=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['border_stroke', b'border_stroke', 'filename_field', b'filename_field', 'fill', b'fill', 'id', b'id', 'name_field', b'name_field', 'path', b'path', 'position', b'position', 'size', b'size']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['border_stroke', b'border_stroke', 'dnp', b'dnp', 'exclude_from_board', b'exclude_from_board', 'exclude_from_bom', b'exclude_from_bom', 'exclude_from_sim', b'exclude_from_sim', 'filename_field', b'filename_field', 'fill', b'fill', 'id', b'id', 'locked', b'locked', 'name_field', b'name_field', 'page_number', b'page_number', 'path', b'path', 'pins', b'pins', 'position', b'position', 'size', b'size', 'user_fields', b'user_fields']) -> None:
        ...
global___SheetSymbol = SheetSymbol

@typing.final
class SchematicPinAlternate(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    NAME_FIELD_NUMBER: builtins.int
    SHAPE_FIELD_NUMBER: builtins.int
    ELECTRICAL_TYPE_FIELD_NUMBER: builtins.int
    name: builtins.str
    shape: global___SchematicPinShape.ValueType
    electrical_type: common.types.base_types_pb2.ElectricalPinType.ValueType

    def __init__(self, *, name: builtins.str=..., shape: global___SchematicPinShape.ValueType=..., electrical_type: common.types.base_types_pb2.ElectricalPinType.ValueType=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['electrical_type', b'electrical_type', 'name', b'name', 'shape', b'shape']) -> None:
        ...
global___SchematicPinAlternate = SchematicPinAlternate

@typing.final
class SchematicPin(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ID_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    NUMBER_FIELD_NUMBER: builtins.int
    POSITION_FIELD_NUMBER: builtins.int
    LENGTH_FIELD_NUMBER: builtins.int
    ORIENTATION_FIELD_NUMBER: builtins.int
    ELECTRICAL_TYPE_FIELD_NUMBER: builtins.int
    SHAPE_FIELD_NUMBER: builtins.int
    VISIBLE_FIELD_NUMBER: builtins.int
    NAME_TEXT_SIZE_FIELD_NUMBER: builtins.int
    NUMBER_TEXT_SIZE_FIELD_NUMBER: builtins.int
    ALTERNATES_FIELD_NUMBER: builtins.int
    ACTIVE_ALTERNATE_FIELD_NUMBER: builtins.int
    name: builtins.str
    number: builtins.str
    orientation: global___SchematicPinOrientation.ValueType
    electrical_type: common.types.base_types_pb2.ElectricalPinType.ValueType
    shape: global___SchematicPinShape.ValueType
    visible: builtins.bool
    active_alternate: builtins.str

    @property
    def id(self) -> common.types.base_types_pb2.KIID:
        ...

    @property
    def position(self) -> common.types.base_types_pb2.Vector2:
        ...

    @property
    def length(self) -> common.types.base_types_pb2.Distance:
        ...

    @property
    def name_text_size(self) -> common.types.base_types_pb2.Distance:
        ...

    @property
    def number_text_size(self) -> common.types.base_types_pb2.Distance:
        ...

    @property
    def alternates(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___SchematicPinAlternate]:
        ...

    def __init__(self, *, id: common.types.base_types_pb2.KIID | None=..., name: builtins.str=..., number: builtins.str=..., position: common.types.base_types_pb2.Vector2 | None=..., length: common.types.base_types_pb2.Distance | None=..., orientation: global___SchematicPinOrientation.ValueType=..., electrical_type: common.types.base_types_pb2.ElectricalPinType.ValueType=..., shape: global___SchematicPinShape.ValueType=..., visible: builtins.bool=..., name_text_size: common.types.base_types_pb2.Distance | None=..., number_text_size: common.types.base_types_pb2.Distance | None=..., alternates: collections.abc.Iterable[global___SchematicPinAlternate] | None=..., active_alternate: builtins.str | None=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['_active_alternate', b'_active_alternate', 'active_alternate', b'active_alternate', 'id', b'id', 'length', b'length', 'name_text_size', b'name_text_size', 'number_text_size', b'number_text_size', 'position', b'position']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['_active_alternate', b'_active_alternate', 'active_alternate', b'active_alternate', 'alternates', b'alternates', 'electrical_type', b'electrical_type', 'id', b'id', 'length', b'length', 'name', b'name', 'name_text_size', b'name_text_size', 'number', b'number', 'number_text_size', b'number_text_size', 'orientation', b'orientation', 'position', b'position', 'shape', b'shape', 'visible', b'visible']) -> None:
        ...

    def WhichOneof(self, oneof_group: typing.Literal['_active_alternate', b'_active_alternate']) -> typing.Literal['active_alternate'] | None:
        ...
global___SchematicPin = SchematicPin

@typing.final
class SchematicSymbolUnit(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    UNIT_FIELD_NUMBER: builtins.int
    unit: builtins.int

    def __init__(self, *, unit: builtins.int=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['unit', b'unit']) -> None:
        ...
global___SchematicSymbolUnit = SchematicSymbolUnit

@typing.final
class SchematicSymbolBodyStyle(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    STYLE_FIELD_NUMBER: builtins.int
    style: builtins.int

    def __init__(self, *, style: builtins.int=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['style', b'style']) -> None:
        ...
global___SchematicSymbolBodyStyle = SchematicSymbolBodyStyle

@typing.final
class SchematicSymbolChild(google.protobuf.message.Message):
    """A schematic item that is stored in a symbol definition"""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ITEM_FIELD_NUMBER: builtins.int
    UNIT_FIELD_NUMBER: builtins.int
    BODY_STYLE_FIELD_NUMBER: builtins.int
    IS_PRIVATE_FIELD_NUMBER: builtins.int
    is_private: builtins.bool
    'Private items are only shown in the symbol editor, not the schematic'

    @property
    def item(self) -> google.protobuf.any_pb2.Any:
        ...

    @property
    def unit(self) -> global___SchematicSymbolUnit:
        """if absent, item is common to all units"""

    @property
    def body_style(self) -> global___SchematicSymbolBodyStyle:
        """if absent, item is common to all body styles"""

    def __init__(self, *, item: google.protobuf.any_pb2.Any | None=..., unit: global___SchematicSymbolUnit | None=..., body_style: global___SchematicSymbolBodyStyle | None=..., is_private: builtins.bool=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['_body_style', b'_body_style', '_unit', b'_unit', 'body_style', b'body_style', 'item', b'item', 'unit', b'unit']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['_body_style', b'_body_style', '_unit', b'_unit', 'body_style', b'body_style', 'is_private', b'is_private', 'item', b'item', 'unit', b'unit']) -> None:
        ...

    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal['_body_style', b'_body_style']) -> typing.Literal['body_style'] | None:
        ...

    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal['_unit', b'_unit']) -> typing.Literal['unit'] | None:
        ...
global___SchematicSymbolChild = SchematicSymbolChild

@typing.final
class SchematicSymbolAttributes(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    EXCLUDE_FROM_SIMULATION_FIELD_NUMBER: builtins.int
    EXCLUDE_FROM_BILL_OF_MATERIALS_FIELD_NUMBER: builtins.int
    EXCLUDE_FROM_BOARD_FIELD_NUMBER: builtins.int
    EXCLUDE_FROM_POSITION_FILES_FIELD_NUMBER: builtins.int
    DO_NOT_POPULATE_FIELD_NUMBER: builtins.int
    exclude_from_simulation: builtins.bool
    exclude_from_bill_of_materials: builtins.bool
    exclude_from_board: builtins.bool
    exclude_from_position_files: builtins.bool
    do_not_populate: builtins.bool

    def __init__(self, *, exclude_from_simulation: builtins.bool=..., exclude_from_bill_of_materials: builtins.bool=..., exclude_from_board: builtins.bool=..., exclude_from_position_files: builtins.bool=..., do_not_populate: builtins.bool=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['do_not_populate', b'do_not_populate', 'exclude_from_bill_of_materials', b'exclude_from_bill_of_materials', 'exclude_from_board', b'exclude_from_board', 'exclude_from_position_files', b'exclude_from_position_files', 'exclude_from_simulation', b'exclude_from_simulation']) -> None:
        ...
global___SchematicSymbolAttributes = SchematicSymbolAttributes

@typing.final
class SchematicSymbolVariant(google.protobuf.message.Message):
    """Data that can change between design variants"""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class FieldsEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor
        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str

        def __init__(self, *, key: builtins.str=..., value: builtins.str=...) -> None:
            ...

        def ClearField(self, field_name: typing.Literal['key', b'key', 'value', b'value']) -> None:
            ...
    NAME_FIELD_NUMBER: builtins.int
    DESCRIPTION_FIELD_NUMBER: builtins.int
    ATTRIBUTES_FIELD_NUMBER: builtins.int
    FIELDS_FIELD_NUMBER: builtins.int
    name: builtins.str
    description: builtins.str

    @property
    def attributes(self) -> global___SchematicSymbolAttributes:
        ...

    @property
    def fields(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]:
        ...

    def __init__(self, *, name: builtins.str=..., description: builtins.str=..., attributes: global___SchematicSymbolAttributes | None=..., fields: collections.abc.Mapping[builtins.str, builtins.str] | None=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['attributes', b'attributes']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['attributes', b'attributes', 'description', b'description', 'fields', b'fields', 'name', b'name']) -> None:
        ...
global___SchematicSymbolVariant = SchematicSymbolVariant

@typing.final
class SchematicSymbol(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ID_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    ATTRIBUTES_FIELD_NUMBER: builtins.int
    REFERENCE_FIELD_FIELD_NUMBER: builtins.int
    VALUE_FIELD_FIELD_NUMBER: builtins.int
    FOOTPRINT_FIELD_FIELD_NUMBER: builtins.int
    DATASHEET_FIELD_FIELD_NUMBER: builtins.int
    DESCRIPTION_FIELD_FIELD_NUMBER: builtins.int
    ITEMS_FIELD_NUMBER: builtins.int
    UNIT_COUNT_FIELD_NUMBER: builtins.int
    BODY_STYLE_COUNT_FIELD_NUMBER: builtins.int
    KEYWORDS_FIELD_NUMBER: builtins.int
    FOOTPRINT_FILTERS_FIELD_NUMBER: builtins.int
    type: global___SchematicSymbolType.ValueType
    unit_count: builtins.int
    body_style_count: builtins.int
    keywords: builtins.str

    @property
    def id(self) -> common.types.base_types_pb2.LibraryIdentifier:
        ...

    @property
    def attributes(self) -> global___SchematicSymbolAttributes:
        ...

    @property
    def reference_field(self) -> global___SchematicField:
        ...

    @property
    def value_field(self) -> global___SchematicField:
        ...

    @property
    def footprint_field(self) -> global___SchematicField:
        ...

    @property
    def datasheet_field(self) -> global___SchematicField:
        ...

    @property
    def description_field(self) -> global___SchematicField:
        ...

    @property
    def items(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___SchematicSymbolChild]:
        """The pins, graphics, text, fields, etc that form the library definition of the symbol"""

    @property
    def footprint_filters(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        ...

    def __init__(self, *, id: common.types.base_types_pb2.LibraryIdentifier | None=..., type: global___SchematicSymbolType.ValueType=..., attributes: global___SchematicSymbolAttributes | None=..., reference_field: global___SchematicField | None=..., value_field: global___SchematicField | None=..., footprint_field: global___SchematicField | None=..., datasheet_field: global___SchematicField | None=..., description_field: global___SchematicField | None=..., items: collections.abc.Iterable[global___SchematicSymbolChild] | None=..., unit_count: builtins.int=..., body_style_count: builtins.int=..., keywords: builtins.str=..., footprint_filters: collections.abc.Iterable[builtins.str] | None=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['attributes', b'attributes', 'datasheet_field', b'datasheet_field', 'description_field', b'description_field', 'footprint_field', b'footprint_field', 'id', b'id', 'reference_field', b'reference_field', 'value_field', b'value_field']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['attributes', b'attributes', 'body_style_count', b'body_style_count', 'datasheet_field', b'datasheet_field', 'description_field', b'description_field', 'footprint_field', b'footprint_field', 'footprint_filters', b'footprint_filters', 'id', b'id', 'items', b'items', 'keywords', b'keywords', 'reference_field', b'reference_field', 'type', b'type', 'unit_count', b'unit_count', 'value_field', b'value_field']) -> None:
        ...
global___SchematicSymbol = SchematicSymbol

@typing.final
class SchematicSymbolTransform(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ORIENTATION_FIELD_NUMBER: builtins.int
    MIRROR_X_FIELD_NUMBER: builtins.int
    MIRROR_Y_FIELD_NUMBER: builtins.int
    orientation: global___SchematicSymbolOrientation.ValueType
    mirror_x: builtins.bool
    mirror_y: builtins.bool

    def __init__(self, *, orientation: global___SchematicSymbolOrientation.ValueType=..., mirror_x: builtins.bool=..., mirror_y: builtins.bool=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['mirror_x', b'mirror_x', 'mirror_y', b'mirror_y', 'orientation', b'orientation']) -> None:
        ...
global___SchematicSymbolTransform = SchematicSymbolTransform

@typing.final
class SchematicSymbolInstance(google.protobuf.message.Message):
    """An instance of a symbol placed on a schematic sheet."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ID_FIELD_NUMBER: builtins.int
    PATH_FIELD_NUMBER: builtins.int
    POSITION_FIELD_NUMBER: builtins.int
    TRANSFORM_FIELD_NUMBER: builtins.int
    LOCKED_FIELD_NUMBER: builtins.int
    DEFINITION_FIELD_NUMBER: builtins.int
    REFERENCE_FIELD_FIELD_NUMBER: builtins.int
    VALUE_FIELD_FIELD_NUMBER: builtins.int
    FOOTPRINT_FIELD_FIELD_NUMBER: builtins.int
    DATASHEET_FIELD_FIELD_NUMBER: builtins.int
    DESCRIPTION_FIELD_FIELD_NUMBER: builtins.int
    ATTRIBUTES_FIELD_NUMBER: builtins.int
    UNIT_FIELD_NUMBER: builtins.int
    BODY_STYLE_FIELD_NUMBER: builtins.int
    SHOW_PIN_NAMES_FIELD_NUMBER: builtins.int
    SHOW_PIN_NUMBERS_FIELD_NUMBER: builtins.int
    PIN_NAME_OFFSET_FIELD_NUMBER: builtins.int
    VARIANTS_FIELD_NUMBER: builtins.int
    locked: common.types.base_types_pb2.LockedState.ValueType
    show_pin_names: builtins.bool
    show_pin_numbers: builtins.bool

    @property
    def id(self) -> common.types.base_types_pb2.KIID:
        ...

    @property
    def path(self) -> common.types.base_types_pb2.SheetPath:
        """Symbol instances may refer to the same graphical symbol from multiple different sheets
        in a hierarchical schematic.  Each instance will have its own reference designator, and
        may also have a different selected unit and other attributes.
        """

    @property
    def position(self) -> common.types.base_types_pb2.Vector2:
        ...

    @property
    def transform(self) -> global___SchematicSymbolTransform:
        ...

    @property
    def definition(self) -> global___SchematicSymbol:
        ...

    @property
    def reference_field(self) -> global___SchematicField:
        ...

    @property
    def value_field(self) -> global___SchematicField:
        ...

    @property
    def footprint_field(self) -> global___SchematicField:
        ...

    @property
    def datasheet_field(self) -> global___SchematicField:
        ...

    @property
    def description_field(self) -> global___SchematicField:
        ...

    @property
    def attributes(self) -> global___SchematicSymbolAttributes:
        ...

    @property
    def unit(self) -> global___SchematicSymbolUnit:
        ...

    @property
    def body_style(self) -> global___SchematicSymbolBodyStyle:
        ...

    @property
    def pin_name_offset(self) -> common.types.base_types_pb2.Distance:
        ...

    @property
    def variants(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___SchematicSymbolVariant]:
        ...

    def __init__(self, *, id: common.types.base_types_pb2.KIID | None=..., path: common.types.base_types_pb2.SheetPath | None=..., position: common.types.base_types_pb2.Vector2 | None=..., transform: global___SchematicSymbolTransform | None=..., locked: common.types.base_types_pb2.LockedState.ValueType=..., definition: global___SchematicSymbol | None=..., reference_field: global___SchematicField | None=..., value_field: global___SchematicField | None=..., footprint_field: global___SchematicField | None=..., datasheet_field: global___SchematicField | None=..., description_field: global___SchematicField | None=..., attributes: global___SchematicSymbolAttributes | None=..., unit: global___SchematicSymbolUnit | None=..., body_style: global___SchematicSymbolBodyStyle | None=..., show_pin_names: builtins.bool=..., show_pin_numbers: builtins.bool=..., pin_name_offset: common.types.base_types_pb2.Distance | None=..., variants: collections.abc.Iterable[global___SchematicSymbolVariant] | None=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['_body_style', b'_body_style', 'attributes', b'attributes', 'body_style', b'body_style', 'datasheet_field', b'datasheet_field', 'definition', b'definition', 'description_field', b'description_field', 'footprint_field', b'footprint_field', 'id', b'id', 'path', b'path', 'pin_name_offset', b'pin_name_offset', 'position', b'position', 'reference_field', b'reference_field', 'transform', b'transform', 'unit', b'unit', 'value_field', b'value_field']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['_body_style', b'_body_style', 'attributes', b'attributes', 'body_style', b'body_style', 'datasheet_field', b'datasheet_field', 'definition', b'definition', 'description_field', b'description_field', 'footprint_field', b'footprint_field', 'id', b'id', 'locked', b'locked', 'path', b'path', 'pin_name_offset', b'pin_name_offset', 'position', b'position', 'reference_field', b'reference_field', 'show_pin_names', b'show_pin_names', 'show_pin_numbers', b'show_pin_numbers', 'transform', b'transform', 'unit', b'unit', 'value_field', b'value_field', 'variants', b'variants']) -> None:
        ...

    def WhichOneof(self, oneof_group: typing.Literal['_body_style', b'_body_style']) -> typing.Literal['body_style'] | None:
        ...
global___SchematicSymbolInstance = SchematicSymbolInstance

@typing.final
class SheetInstance(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    PATH_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    FILENAME_FIELD_NUMBER: builtins.int
    PAGE_NUMBER_FIELD_NUMBER: builtins.int
    CHILDREN_FIELD_NUMBER: builtins.int
    name: builtins.str
    filename: builtins.str
    page_number: builtins.str

    @property
    def path(self) -> common.types.base_types_pb2.SheetPath:
        ...

    @property
    def children(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___SheetInstance]:
        ...

    def __init__(self, *, path: common.types.base_types_pb2.SheetPath | None=..., name: builtins.str=..., filename: builtins.str=..., page_number: builtins.str=..., children: collections.abc.Iterable[global___SheetInstance] | None=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['path', b'path']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['children', b'children', 'filename', b'filename', 'name', b'name', 'page_number', b'page_number', 'path', b'path']) -> None:
        ...
global___SheetInstance = SheetInstance

@typing.final
class SchematicNetSheetContents(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    PATH_FIELD_NUMBER: builtins.int
    ITEMS_FIELD_NUMBER: builtins.int

    @property
    def path(self) -> common.types.base_types_pb2.SheetPath:
        ...

    @property
    def items(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[common.types.base_types_pb2.KIID]:
        ...

    def __init__(self, *, path: common.types.base_types_pb2.SheetPath | None=..., items: collections.abc.Iterable[common.types.base_types_pb2.KIID] | None=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['path', b'path']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['items', b'items', 'path', b'path']) -> None:
        ...
global___SchematicNetSheetContents = SchematicNetSheetContents

@typing.final
class SchematicNet(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    NAME_FIELD_NUMBER: builtins.int
    SHEETS_FIELD_NUMBER: builtins.int
    name: builtins.str

    @property
    def sheets(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___SchematicNetSheetContents]:
        ...

    def __init__(self, *, name: builtins.str=..., sheets: collections.abc.Iterable[global___SchematicNetSheetContents] | None=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['name', b'name', 'sheets', b'sheets']) -> None:
        ...
global___SchematicNet = SchematicNet