"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file

This program source code file is part of KiCad, a free EDA CAD application.

Copyright (C) 2024 Jon Evans <jon@craftyjon.com>
Copyright (C) 2024 KiCad Developers, see AUTHORS.txt for contributors.

This program is free software: you can redistribute it and/or modify it
under the terms of the GNU General Public License as published by the
Free Software Foundation, either version 3 of the License, or (at your
option) any later version.

This program is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License along
with this program.  If not, see <http://www.gnu.org/licenses/>.
"""
from .. import board
import builtins
import collections.abc
from .. import common
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing
if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions
DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _BoardStackupLayerType:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _BoardStackupLayerTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_BoardStackupLayerType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    BSLT_UNKNOWN: _BoardStackupLayerType.ValueType
    BSLT_COPPER: _BoardStackupLayerType.ValueType
    BSLT_DIELECTRIC: _BoardStackupLayerType.ValueType
    BSLT_SILKSCREEN: _BoardStackupLayerType.ValueType
    BSLT_SOLDERMASK: _BoardStackupLayerType.ValueType
    BSLT_SOLDERPASTE: _BoardStackupLayerType.ValueType
    BSLT_UNDEFINED: _BoardStackupLayerType.ValueType

class BoardStackupLayerType(_BoardStackupLayerType, metaclass=_BoardStackupLayerTypeEnumTypeWrapper):
    ...
BSLT_UNKNOWN: BoardStackupLayerType.ValueType
BSLT_COPPER: BoardStackupLayerType.ValueType
BSLT_DIELECTRIC: BoardStackupLayerType.ValueType
BSLT_SILKSCREEN: BoardStackupLayerType.ValueType
BSLT_SOLDERMASK: BoardStackupLayerType.ValueType
BSLT_SOLDERPASTE: BoardStackupLayerType.ValueType
BSLT_UNDEFINED: BoardStackupLayerType.ValueType
global___BoardStackupLayerType = BoardStackupLayerType

class _BoardLayerClass:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _BoardLayerClassEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_BoardLayerClass.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    BLC_UNKNOWN: _BoardLayerClass.ValueType
    BLC_SILKSCREEN: _BoardLayerClass.ValueType
    BLC_COPPER: _BoardLayerClass.ValueType
    BLC_EDGES: _BoardLayerClass.ValueType
    BLC_COURTYARD: _BoardLayerClass.ValueType
    BLC_FABRICATION: _BoardLayerClass.ValueType
    BLC_OTHER: _BoardLayerClass.ValueType

class BoardLayerClass(_BoardLayerClass, metaclass=_BoardLayerClassEnumTypeWrapper):
    """LAYER_CLASS_* in BOARD_DESIGN_SETTINGS -- needs to become an enum class"""
BLC_UNKNOWN: BoardLayerClass.ValueType
BLC_SILKSCREEN: BoardLayerClass.ValueType
BLC_COPPER: BoardLayerClass.ValueType
BLC_EDGES: BoardLayerClass.ValueType
BLC_COURTYARD: BoardLayerClass.ValueType
BLC_FABRICATION: BoardLayerClass.ValueType
BLC_OTHER: BoardLayerClass.ValueType
global___BoardLayerClass = BoardLayerClass

class _TeardropTarget:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _TeardropTargetEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_TeardropTarget.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    TDT_UNKNOWN: _TeardropTarget.ValueType
    TDT_ROUND: _TeardropTarget.ValueType
    TDT_RECT: _TeardropTarget.ValueType
    TDT_TRACK: _TeardropTarget.ValueType

class TeardropTarget(_TeardropTarget, metaclass=_TeardropTargetEnumTypeWrapper):
    ...
TDT_UNKNOWN: TeardropTarget.ValueType
TDT_ROUND: TeardropTarget.ValueType
TDT_RECT: TeardropTarget.ValueType
TDT_TRACK: TeardropTarget.ValueType
global___TeardropTarget = TeardropTarget

class _DrcErrorType:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _DrcErrorTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_DrcErrorType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    DRCET_UNKNOWN: _DrcErrorType.ValueType
    DRCET_UNCONNECTED_ITEMS: _DrcErrorType.ValueType
    DRCET_SHORTING_ITEMS: _DrcErrorType.ValueType
    DRCET_ALLOWED_ITEMS: _DrcErrorType.ValueType
    DRCET_TEXT_ON_EDGECUTS: _DrcErrorType.ValueType
    DRCET_CLEARANCE: _DrcErrorType.ValueType
    DRCET_CREEPAGE: _DrcErrorType.ValueType
    DRCET_TRACKS_CROSSING: _DrcErrorType.ValueType
    DRCET_EDGE_CLEARANCE: _DrcErrorType.ValueType
    DRCET_ZONES_INTERSECT: _DrcErrorType.ValueType
    DRCET_ISOLATED_COPPER: _DrcErrorType.ValueType
    DRCET_STARVED_THERMAL: _DrcErrorType.ValueType
    DRCET_DANGLING_VIA: _DrcErrorType.ValueType
    DRCET_DANGLING_TRACK: _DrcErrorType.ValueType
    DRCET_DRILLED_HOLES_TOO_CLOSE: _DrcErrorType.ValueType
    DRCET_DRILLED_HOLES_COLOCATED: _DrcErrorType.ValueType
    DRCET_HOLE_CLEARANCE: _DrcErrorType.ValueType
    DRCET_CONNECTION_WIDTH: _DrcErrorType.ValueType
    DRCET_TRACK_WIDTH: _DrcErrorType.ValueType
    DRCET_TRACK_ANGLE: _DrcErrorType.ValueType
    DRCET_TRACK_SEGMENT_LENGTH: _DrcErrorType.ValueType
    DRCET_ANNULAR_WIDTH: _DrcErrorType.ValueType
    DRCET_DRILL_OUT_OF_RANGE: _DrcErrorType.ValueType
    DRCET_VIA_DIAMETER: _DrcErrorType.ValueType
    DRCET_PADSTACK: _DrcErrorType.ValueType
    DRCET_PADSTACK_INVALID: _DrcErrorType.ValueType
    DRCET_MICROVIA_DRILL_OUT_OF_RANGE: _DrcErrorType.ValueType
    DRCET_OVERLAPPING_FOOTPRINTS: _DrcErrorType.ValueType
    DRCET_MISSING_COURTYARD: _DrcErrorType.ValueType
    DRCET_MALFORMED_COURTYARD: _DrcErrorType.ValueType
    DRCET_PTH_IN_COURTYARD: _DrcErrorType.ValueType
    DRCET_NPTH_IN_COURTYARD: _DrcErrorType.ValueType
    DRCET_DISABLED_LAYER_ITEM: _DrcErrorType.ValueType
    DRCET_INVALID_OUTLINE: _DrcErrorType.ValueType
    DRCET_MISSING_FOOTPRINT: _DrcErrorType.ValueType
    DRCET_DUPLICATE_FOOTPRINT: _DrcErrorType.ValueType
    DRCET_NET_CONFLICT: _DrcErrorType.ValueType
    DRCET_EXTRA_FOOTPRINT: _DrcErrorType.ValueType
    DRCET_SCHEMATIC_PARITY: _DrcErrorType.ValueType
    DRCET_SCHEMATIC_FIELDS_PARITY: _DrcErrorType.ValueType
    DRCET_FOOTPRINT_FILTERS: _DrcErrorType.ValueType
    DRCET_LIB_FOOTPRINT_ISSUES: _DrcErrorType.ValueType
    DRCET_LIB_FOOTPRINT_MISMATCH: _DrcErrorType.ValueType
    DRCET_UNRESOLVED_VARIABLE: _DrcErrorType.ValueType
    DRCET_ASSERTION_FAILURE: _DrcErrorType.ValueType
    DRCET_GENERIC_WARNING: _DrcErrorType.ValueType
    DRCET_GENERIC_ERROR: _DrcErrorType.ValueType
    DRCET_COPPER_SLIVER: _DrcErrorType.ValueType
    DRCET_SILK_CLEARANCE: _DrcErrorType.ValueType
    DRCET_SILK_MASK_CLEARANCE: _DrcErrorType.ValueType
    DRCET_SILK_EDGE_CLEARANCE: _DrcErrorType.ValueType
    DRCET_SOLDERMASK_BRIDGE: _DrcErrorType.ValueType
    DRCET_TEXT_HEIGHT: _DrcErrorType.ValueType
    DRCET_TEXT_THICKNESS: _DrcErrorType.ValueType
    DRCET_LENGTH_OUT_OF_RANGE: _DrcErrorType.ValueType
    DRCET_SKEW_OUT_OF_RANGE: _DrcErrorType.ValueType
    DRCET_VIA_COUNT_OUT_OF_RANGE: _DrcErrorType.ValueType
    DRCET_DIFF_PAIR_GAP_OUT_OF_RANGE: _DrcErrorType.ValueType
    DRCET_DIFF_PAIR_UNCOUPLED_LENGTH_TOO_LONG: _DrcErrorType.ValueType
    DRCET_FOOTPRINT: _DrcErrorType.ValueType
    DRCET_FOOTPRINT_TYPE_MISMATCH: _DrcErrorType.ValueType
    DRCET_PAD_TH_WITH_NO_HOLE: _DrcErrorType.ValueType
    DRCET_MIRRORED_TEXT_ON_FRONT_LAYER: _DrcErrorType.ValueType
    DRCET_NONMIRRORED_TEXT_ON_BACK_LAYER: _DrcErrorType.ValueType
    DRCET_MISSING_TUNING_PROFILE: _DrcErrorType.ValueType
    DRCET_TUNING_PROFILE_IMPLICIT_RULES: _DrcErrorType.ValueType
    DRCET_TRACK_ON_POST_MACHINED_LAYER: _DrcErrorType.ValueType
    DRCET_TRACK_NOT_CENTERED_ON_VIA: _DrcErrorType.ValueType

class DrcErrorType(_DrcErrorType, metaclass=_DrcErrorTypeEnumTypeWrapper):
    ...
DRCET_UNKNOWN: DrcErrorType.ValueType
DRCET_UNCONNECTED_ITEMS: DrcErrorType.ValueType
DRCET_SHORTING_ITEMS: DrcErrorType.ValueType
DRCET_ALLOWED_ITEMS: DrcErrorType.ValueType
DRCET_TEXT_ON_EDGECUTS: DrcErrorType.ValueType
DRCET_CLEARANCE: DrcErrorType.ValueType
DRCET_CREEPAGE: DrcErrorType.ValueType
DRCET_TRACKS_CROSSING: DrcErrorType.ValueType
DRCET_EDGE_CLEARANCE: DrcErrorType.ValueType
DRCET_ZONES_INTERSECT: DrcErrorType.ValueType
DRCET_ISOLATED_COPPER: DrcErrorType.ValueType
DRCET_STARVED_THERMAL: DrcErrorType.ValueType
DRCET_DANGLING_VIA: DrcErrorType.ValueType
DRCET_DANGLING_TRACK: DrcErrorType.ValueType
DRCET_DRILLED_HOLES_TOO_CLOSE: DrcErrorType.ValueType
DRCET_DRILLED_HOLES_COLOCATED: DrcErrorType.ValueType
DRCET_HOLE_CLEARANCE: DrcErrorType.ValueType
DRCET_CONNECTION_WIDTH: DrcErrorType.ValueType
DRCET_TRACK_WIDTH: DrcErrorType.ValueType
DRCET_TRACK_ANGLE: DrcErrorType.ValueType
DRCET_TRACK_SEGMENT_LENGTH: DrcErrorType.ValueType
DRCET_ANNULAR_WIDTH: DrcErrorType.ValueType
DRCET_DRILL_OUT_OF_RANGE: DrcErrorType.ValueType
DRCET_VIA_DIAMETER: DrcErrorType.ValueType
DRCET_PADSTACK: DrcErrorType.ValueType
DRCET_PADSTACK_INVALID: DrcErrorType.ValueType
DRCET_MICROVIA_DRILL_OUT_OF_RANGE: DrcErrorType.ValueType
DRCET_OVERLAPPING_FOOTPRINTS: DrcErrorType.ValueType
DRCET_MISSING_COURTYARD: DrcErrorType.ValueType
DRCET_MALFORMED_COURTYARD: DrcErrorType.ValueType
DRCET_PTH_IN_COURTYARD: DrcErrorType.ValueType
DRCET_NPTH_IN_COURTYARD: DrcErrorType.ValueType
DRCET_DISABLED_LAYER_ITEM: DrcErrorType.ValueType
DRCET_INVALID_OUTLINE: DrcErrorType.ValueType
DRCET_MISSING_FOOTPRINT: DrcErrorType.ValueType
DRCET_DUPLICATE_FOOTPRINT: DrcErrorType.ValueType
DRCET_NET_CONFLICT: DrcErrorType.ValueType
DRCET_EXTRA_FOOTPRINT: DrcErrorType.ValueType
DRCET_SCHEMATIC_PARITY: DrcErrorType.ValueType
DRCET_SCHEMATIC_FIELDS_PARITY: DrcErrorType.ValueType
DRCET_FOOTPRINT_FILTERS: DrcErrorType.ValueType
DRCET_LIB_FOOTPRINT_ISSUES: DrcErrorType.ValueType
DRCET_LIB_FOOTPRINT_MISMATCH: DrcErrorType.ValueType
DRCET_UNRESOLVED_VARIABLE: DrcErrorType.ValueType
DRCET_ASSERTION_FAILURE: DrcErrorType.ValueType
DRCET_GENERIC_WARNING: DrcErrorType.ValueType
DRCET_GENERIC_ERROR: DrcErrorType.ValueType
DRCET_COPPER_SLIVER: DrcErrorType.ValueType
DRCET_SILK_CLEARANCE: DrcErrorType.ValueType
DRCET_SILK_MASK_CLEARANCE: DrcErrorType.ValueType
DRCET_SILK_EDGE_CLEARANCE: DrcErrorType.ValueType
DRCET_SOLDERMASK_BRIDGE: DrcErrorType.ValueType
DRCET_TEXT_HEIGHT: DrcErrorType.ValueType
DRCET_TEXT_THICKNESS: DrcErrorType.ValueType
DRCET_LENGTH_OUT_OF_RANGE: DrcErrorType.ValueType
DRCET_SKEW_OUT_OF_RANGE: DrcErrorType.ValueType
DRCET_VIA_COUNT_OUT_OF_RANGE: DrcErrorType.ValueType
DRCET_DIFF_PAIR_GAP_OUT_OF_RANGE: DrcErrorType.ValueType
DRCET_DIFF_PAIR_UNCOUPLED_LENGTH_TOO_LONG: DrcErrorType.ValueType
DRCET_FOOTPRINT: DrcErrorType.ValueType
DRCET_FOOTPRINT_TYPE_MISMATCH: DrcErrorType.ValueType
DRCET_PAD_TH_WITH_NO_HOLE: DrcErrorType.ValueType
DRCET_MIRRORED_TEXT_ON_FRONT_LAYER: DrcErrorType.ValueType
DRCET_NONMIRRORED_TEXT_ON_BACK_LAYER: DrcErrorType.ValueType
DRCET_MISSING_TUNING_PROFILE: DrcErrorType.ValueType
DRCET_TUNING_PROFILE_IMPLICIT_RULES: DrcErrorType.ValueType
DRCET_TRACK_ON_POST_MACHINED_LAYER: DrcErrorType.ValueType
DRCET_TRACK_NOT_CENTERED_ON_VIA: DrcErrorType.ValueType
global___DrcErrorType = DrcErrorType

class _CustomRuleLayerMode:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _CustomRuleLayerModeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_CustomRuleLayerMode.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    CRLM_UNKNOWN: _CustomRuleLayerMode.ValueType
    CRLM_OUTER: _CustomRuleLayerMode.ValueType
    CRLM_INNER: _CustomRuleLayerMode.ValueType

class CustomRuleLayerMode(_CustomRuleLayerMode, metaclass=_CustomRuleLayerModeEnumTypeWrapper):
    ...
CRLM_UNKNOWN: CustomRuleLayerMode.ValueType
CRLM_OUTER: CustomRuleLayerMode.ValueType
CRLM_INNER: CustomRuleLayerMode.ValueType
global___CustomRuleLayerMode = CustomRuleLayerMode

class _CustomRuleConstraintType:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _CustomRuleConstraintTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_CustomRuleConstraintType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    CRCT_UNKNOWN: _CustomRuleConstraintType.ValueType
    CRCT_CLEARANCE: _CustomRuleConstraintType.ValueType
    CRCT_CREEPAGE: _CustomRuleConstraintType.ValueType
    CRCT_HOLE_CLEARANCE: _CustomRuleConstraintType.ValueType
    CRCT_HOLE_TO_HOLE: _CustomRuleConstraintType.ValueType
    CRCT_EDGE_CLEARANCE: _CustomRuleConstraintType.ValueType
    CRCT_HOLE_SIZE: _CustomRuleConstraintType.ValueType
    CRCT_COURTYARD_CLEARANCE: _CustomRuleConstraintType.ValueType
    CRCT_SILK_CLEARANCE: _CustomRuleConstraintType.ValueType
    CRCT_TEXT_HEIGHT: _CustomRuleConstraintType.ValueType
    CRCT_TEXT_THICKNESS: _CustomRuleConstraintType.ValueType
    CRCT_TRACK_WIDTH: _CustomRuleConstraintType.ValueType
    CRCT_TRACK_SEGMENT_LENGTH: _CustomRuleConstraintType.ValueType
    CRCT_ANNULAR_WIDTH: _CustomRuleConstraintType.ValueType
    CRCT_ZONE_CONNECTION: _CustomRuleConstraintType.ValueType
    CRCT_THERMAL_RELIEF_GAP: _CustomRuleConstraintType.ValueType
    CRCT_THERMAL_SPOKE_WIDTH: _CustomRuleConstraintType.ValueType
    CRCT_MIN_RESOLVED_SPOKES: _CustomRuleConstraintType.ValueType
    CRCT_SOLDER_MASK_EXPANSION: _CustomRuleConstraintType.ValueType
    CRCT_SOLDER_PASTE_ABS_MARGIN: _CustomRuleConstraintType.ValueType
    CRCT_SOLDER_PASTE_REL_MARGIN: _CustomRuleConstraintType.ValueType
    CRCT_DISALLOW: _CustomRuleConstraintType.ValueType
    CRCT_VIA_DIAMETER: _CustomRuleConstraintType.ValueType
    CRCT_LENGTH: _CustomRuleConstraintType.ValueType
    CRCT_SKEW: _CustomRuleConstraintType.ValueType
    CRCT_DIFF_PAIR_GAP: _CustomRuleConstraintType.ValueType
    CRCT_MAX_UNCOUPLED: _CustomRuleConstraintType.ValueType
    CRCT_DIFF_PAIR_INTRA_SKEW: _CustomRuleConstraintType.ValueType
    CRCT_VIA_COUNT: _CustomRuleConstraintType.ValueType
    CRCT_PHYSICAL_CLEARANCE: _CustomRuleConstraintType.ValueType
    CRCT_PHYSICAL_HOLE_CLEARANCE: _CustomRuleConstraintType.ValueType
    CRCT_ASSERTION: _CustomRuleConstraintType.ValueType
    CRCT_CONNECTION_WIDTH: _CustomRuleConstraintType.ValueType
    CRCT_TRACK_ANGLE: _CustomRuleConstraintType.ValueType
    CRCT_VIA_DANGLING: _CustomRuleConstraintType.ValueType
    CRCT_BRIDGED_MASK: _CustomRuleConstraintType.ValueType
    CRCT_SOLDER_MASK_SLIVER: _CustomRuleConstraintType.ValueType

class CustomRuleConstraintType(_CustomRuleConstraintType, metaclass=_CustomRuleConstraintTypeEnumTypeWrapper):
    ...
CRCT_UNKNOWN: CustomRuleConstraintType.ValueType
CRCT_CLEARANCE: CustomRuleConstraintType.ValueType
CRCT_CREEPAGE: CustomRuleConstraintType.ValueType
CRCT_HOLE_CLEARANCE: CustomRuleConstraintType.ValueType
CRCT_HOLE_TO_HOLE: CustomRuleConstraintType.ValueType
CRCT_EDGE_CLEARANCE: CustomRuleConstraintType.ValueType
CRCT_HOLE_SIZE: CustomRuleConstraintType.ValueType
CRCT_COURTYARD_CLEARANCE: CustomRuleConstraintType.ValueType
CRCT_SILK_CLEARANCE: CustomRuleConstraintType.ValueType
CRCT_TEXT_HEIGHT: CustomRuleConstraintType.ValueType
CRCT_TEXT_THICKNESS: CustomRuleConstraintType.ValueType
CRCT_TRACK_WIDTH: CustomRuleConstraintType.ValueType
CRCT_TRACK_SEGMENT_LENGTH: CustomRuleConstraintType.ValueType
CRCT_ANNULAR_WIDTH: CustomRuleConstraintType.ValueType
CRCT_ZONE_CONNECTION: CustomRuleConstraintType.ValueType
CRCT_THERMAL_RELIEF_GAP: CustomRuleConstraintType.ValueType
CRCT_THERMAL_SPOKE_WIDTH: CustomRuleConstraintType.ValueType
CRCT_MIN_RESOLVED_SPOKES: CustomRuleConstraintType.ValueType
CRCT_SOLDER_MASK_EXPANSION: CustomRuleConstraintType.ValueType
CRCT_SOLDER_PASTE_ABS_MARGIN: CustomRuleConstraintType.ValueType
CRCT_SOLDER_PASTE_REL_MARGIN: CustomRuleConstraintType.ValueType
CRCT_DISALLOW: CustomRuleConstraintType.ValueType
CRCT_VIA_DIAMETER: CustomRuleConstraintType.ValueType
CRCT_LENGTH: CustomRuleConstraintType.ValueType
CRCT_SKEW: CustomRuleConstraintType.ValueType
CRCT_DIFF_PAIR_GAP: CustomRuleConstraintType.ValueType
CRCT_MAX_UNCOUPLED: CustomRuleConstraintType.ValueType
CRCT_DIFF_PAIR_INTRA_SKEW: CustomRuleConstraintType.ValueType
CRCT_VIA_COUNT: CustomRuleConstraintType.ValueType
CRCT_PHYSICAL_CLEARANCE: CustomRuleConstraintType.ValueType
CRCT_PHYSICAL_HOLE_CLEARANCE: CustomRuleConstraintType.ValueType
CRCT_ASSERTION: CustomRuleConstraintType.ValueType
CRCT_CONNECTION_WIDTH: CustomRuleConstraintType.ValueType
CRCT_TRACK_ANGLE: CustomRuleConstraintType.ValueType
CRCT_VIA_DANGLING: CustomRuleConstraintType.ValueType
CRCT_BRIDGED_MASK: CustomRuleConstraintType.ValueType
CRCT_SOLDER_MASK_SLIVER: CustomRuleConstraintType.ValueType
global___CustomRuleConstraintType = CustomRuleConstraintType

class _CustomRuleConstraintOption:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _CustomRuleConstraintOptionEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_CustomRuleConstraintOption.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    CRCO_UNKNOWN: _CustomRuleConstraintOption.ValueType
    CRCO_SKEW_WITHIN_DIFF_PAIRS: _CustomRuleConstraintOption.ValueType
    CRCO_SPACE_DOMAIN: _CustomRuleConstraintOption.ValueType
    CRCO_TIME_DOMAIN: _CustomRuleConstraintOption.ValueType

class CustomRuleConstraintOption(_CustomRuleConstraintOption, metaclass=_CustomRuleConstraintOptionEnumTypeWrapper):
    ...
CRCO_UNKNOWN: CustomRuleConstraintOption.ValueType
CRCO_SKEW_WITHIN_DIFF_PAIRS: CustomRuleConstraintOption.ValueType
CRCO_SPACE_DOMAIN: CustomRuleConstraintOption.ValueType
CRCO_TIME_DOMAIN: CustomRuleConstraintOption.ValueType
global___CustomRuleConstraintOption = CustomRuleConstraintOption

class _CustomRuleDisallowType:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _CustomRuleDisallowTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_CustomRuleDisallowType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    CRDT_UNKNOWN: _CustomRuleDisallowType.ValueType
    CRDT_THROUGH_VIAS: _CustomRuleDisallowType.ValueType
    CRDT_MICRO_VIAS: _CustomRuleDisallowType.ValueType
    CRDT_BLIND_VIAS: _CustomRuleDisallowType.ValueType
    CRDT_BURIED_VIAS: _CustomRuleDisallowType.ValueType
    CRDT_TRACKS: _CustomRuleDisallowType.ValueType
    CRDT_PADS: _CustomRuleDisallowType.ValueType
    CRDT_ZONES: _CustomRuleDisallowType.ValueType
    CRDT_TEXTS: _CustomRuleDisallowType.ValueType
    CRDT_GRAPHICS: _CustomRuleDisallowType.ValueType
    CRDT_HOLES: _CustomRuleDisallowType.ValueType
    CRDT_FOOTPRINTS: _CustomRuleDisallowType.ValueType

class CustomRuleDisallowType(_CustomRuleDisallowType, metaclass=_CustomRuleDisallowTypeEnumTypeWrapper):
    ...
CRDT_UNKNOWN: CustomRuleDisallowType.ValueType
CRDT_THROUGH_VIAS: CustomRuleDisallowType.ValueType
CRDT_MICRO_VIAS: CustomRuleDisallowType.ValueType
CRDT_BLIND_VIAS: CustomRuleDisallowType.ValueType
CRDT_BURIED_VIAS: CustomRuleDisallowType.ValueType
CRDT_TRACKS: CustomRuleDisallowType.ValueType
CRDT_PADS: CustomRuleDisallowType.ValueType
CRDT_ZONES: CustomRuleDisallowType.ValueType
CRDT_TEXTS: CustomRuleDisallowType.ValueType
CRDT_GRAPHICS: CustomRuleDisallowType.ValueType
CRDT_HOLES: CustomRuleDisallowType.ValueType
CRDT_FOOTPRINTS: CustomRuleDisallowType.ValueType
global___CustomRuleDisallowType = CustomRuleDisallowType

@typing.final
class BoardFinish(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    TYPE_NAME_FIELD_NUMBER: builtins.int
    type_name: builtins.str

    def __init__(self, *, type_name: builtins.str=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['type_name', b'type_name']) -> None:
        ...
global___BoardFinish = BoardFinish

@typing.final
class BoardImpedanceControl(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    IS_CONTROLLED_FIELD_NUMBER: builtins.int
    is_controlled: builtins.bool

    def __init__(self, *, is_controlled: builtins.bool=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['is_controlled', b'is_controlled']) -> None:
        ...
global___BoardImpedanceControl = BoardImpedanceControl

@typing.final
class BoardEdgeConnector(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(self) -> None:
        ...
global___BoardEdgeConnector = BoardEdgeConnector

@typing.final
class Castellation(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    HAS_CASTELLATED_PADS_FIELD_NUMBER: builtins.int
    has_castellated_pads: builtins.bool

    def __init__(self, *, has_castellated_pads: builtins.bool=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['has_castellated_pads', b'has_castellated_pads']) -> None:
        ...
global___Castellation = Castellation

@typing.final
class EdgePlating(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    HAS_EDGE_PLATING_FIELD_NUMBER: builtins.int
    has_edge_plating: builtins.bool

    def __init__(self, *, has_edge_plating: builtins.bool=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['has_edge_plating', b'has_edge_plating']) -> None:
        ...
global___EdgePlating = EdgePlating

@typing.final
class BoardEdgeSettings(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    CONNECTOR_FIELD_NUMBER: builtins.int
    CASTELLATION_FIELD_NUMBER: builtins.int
    PLATING_FIELD_NUMBER: builtins.int

    @property
    def connector(self) -> global___BoardEdgeConnector:
        ...

    @property
    def castellation(self) -> global___Castellation:
        ...

    @property
    def plating(self) -> global___EdgePlating:
        ...

    def __init__(self, *, connector: global___BoardEdgeConnector | None=..., castellation: global___Castellation | None=..., plating: global___EdgePlating | None=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['castellation', b'castellation', 'connector', b'connector', 'plating', b'plating']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['castellation', b'castellation', 'connector', b'connector', 'plating', b'plating']) -> None:
        ...
global___BoardEdgeSettings = BoardEdgeSettings

@typing.final
class BoardStackupCopperLayer(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(self) -> None:
        ...
global___BoardStackupCopperLayer = BoardStackupCopperLayer

@typing.final
class BoardStackupDielectricProperties(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    EPSILON_R_FIELD_NUMBER: builtins.int
    LOSS_TANGENT_FIELD_NUMBER: builtins.int
    MATERIAL_NAME_FIELD_NUMBER: builtins.int
    THICKNESS_FIELD_NUMBER: builtins.int
    epsilon_r: builtins.float
    loss_tangent: builtins.float
    material_name: builtins.str

    @property
    def thickness(self) -> common.types.base_types_pb2.Distance:
        ...

    def __init__(self, *, epsilon_r: builtins.float=..., loss_tangent: builtins.float=..., material_name: builtins.str=..., thickness: common.types.base_types_pb2.Distance | None=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['thickness', b'thickness']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['epsilon_r', b'epsilon_r', 'loss_tangent', b'loss_tangent', 'material_name', b'material_name', 'thickness', b'thickness']) -> None:
        ...
global___BoardStackupDielectricProperties = BoardStackupDielectricProperties

@typing.final
class BoardStackupDielectricLayer(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    LAYER_FIELD_NUMBER: builtins.int

    @property
    def layer(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___BoardStackupDielectricProperties]:
        """A single dielectric slot (between copper layers) can be made up of multiple physical layers"""

    def __init__(self, *, layer: collections.abc.Iterable[global___BoardStackupDielectricProperties] | None=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['layer', b'layer']) -> None:
        ...
global___BoardStackupDielectricLayer = BoardStackupDielectricLayer

@typing.final
class BoardStackupLayer(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    THICKNESS_FIELD_NUMBER: builtins.int
    LAYER_FIELD_NUMBER: builtins.int
    ENABLED_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    DIELECTRIC_FIELD_NUMBER: builtins.int
    COLOR_FIELD_NUMBER: builtins.int
    MATERIAL_NAME_FIELD_NUMBER: builtins.int
    USER_NAME_FIELD_NUMBER: builtins.int
    layer: board.board_types_pb2.BoardLayer.ValueType
    enabled: builtins.bool
    type: global___BoardStackupLayerType.ValueType
    material_name: builtins.str
    user_name: builtins.str
    'The name of the layer shown in the KiCad GUI, which may be a default value like "F.Cu" or may\n    have been customized by the user.  This field does not apply to dielectric layers.\n    '

    @property
    def thickness(self) -> common.types.base_types_pb2.Distance:
        ...

    @property
    def dielectric(self) -> global___BoardStackupDielectricLayer:
        ...

    @property
    def color(self) -> common.types.base_types_pb2.Color:
        ...

    def __init__(self, *, thickness: common.types.base_types_pb2.Distance | None=..., layer: board.board_types_pb2.BoardLayer.ValueType=..., enabled: builtins.bool=..., type: global___BoardStackupLayerType.ValueType=..., dielectric: global___BoardStackupDielectricLayer | None=..., color: common.types.base_types_pb2.Color | None=..., material_name: builtins.str=..., user_name: builtins.str=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['color', b'color', 'dielectric', b'dielectric', 'thickness', b'thickness']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['color', b'color', 'dielectric', b'dielectric', 'enabled', b'enabled', 'layer', b'layer', 'material_name', b'material_name', 'thickness', b'thickness', 'type', b'type', 'user_name', b'user_name']) -> None:
        ...
global___BoardStackupLayer = BoardStackupLayer

@typing.final
class BoardStackup(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    FINISH_FIELD_NUMBER: builtins.int
    IMPEDANCE_FIELD_NUMBER: builtins.int
    EDGE_FIELD_NUMBER: builtins.int
    LAYERS_FIELD_NUMBER: builtins.int

    @property
    def finish(self) -> global___BoardFinish:
        ...

    @property
    def impedance(self) -> global___BoardImpedanceControl:
        ...

    @property
    def edge(self) -> global___BoardEdgeSettings:
        """NOTE: m_HasThicknessConstrains appears to be unused"""

    @property
    def layers(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___BoardStackupLayer]:
        ...

    def __init__(self, *, finish: global___BoardFinish | None=..., impedance: global___BoardImpedanceControl | None=..., edge: global___BoardEdgeSettings | None=..., layers: collections.abc.Iterable[global___BoardStackupLayer] | None=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['edge', b'edge', 'finish', b'finish', 'impedance', b'impedance']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['edge', b'edge', 'finish', b'finish', 'impedance', b'impedance', 'layers', b'layers']) -> None:
        ...
global___BoardStackup = BoardStackup

@typing.final
class BoardLayerGraphicsDefaults(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    LAYER_FIELD_NUMBER: builtins.int
    TEXT_FIELD_NUMBER: builtins.int
    LINE_THICKNESS_FIELD_NUMBER: builtins.int
    layer: global___BoardLayerClass.ValueType

    @property
    def text(self) -> common.types.base_types_pb2.TextAttributes:
        ...

    @property
    def line_thickness(self) -> common.types.base_types_pb2.Distance:
        ...

    def __init__(self, *, layer: global___BoardLayerClass.ValueType=..., text: common.types.base_types_pb2.TextAttributes | None=..., line_thickness: common.types.base_types_pb2.Distance | None=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['line_thickness', b'line_thickness', 'text', b'text']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['layer', b'layer', 'line_thickness', b'line_thickness', 'text', b'text']) -> None:
        ...
global___BoardLayerGraphicsDefaults = BoardLayerGraphicsDefaults

@typing.final
class GraphicsDefaults(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    LAYERS_FIELD_NUMBER: builtins.int

    @property
    def layers(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___BoardLayerGraphicsDefaults]:
        ...

    def __init__(self, *, layers: collections.abc.Iterable[global___BoardLayerGraphicsDefaults] | None=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['layers', b'layers']) -> None:
        ...
global___GraphicsDefaults = GraphicsDefaults

@typing.final
class BoardSettings(google.protobuf.message.Message):
    """Anything that isn't stackup or design rules"""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    GRAPHICS_DEFAULTS_FIELD_NUMBER: builtins.int

    @property
    def graphics_defaults(self) -> global___GraphicsDefaults:
        """Dimension default settings"""

    def __init__(self, *, graphics_defaults: global___GraphicsDefaults | None=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['graphics_defaults', b'graphics_defaults']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['graphics_defaults', b'graphics_defaults']) -> None:
        ...
global___BoardSettings = BoardSettings

@typing.final
class MinimumConstraints(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    MIN_CLEARANCE_FIELD_NUMBER: builtins.int
    MIN_GROOVE_WIDTH_FIELD_NUMBER: builtins.int
    MIN_CONNECTION_WIDTH_FIELD_NUMBER: builtins.int
    MIN_TRACK_WIDTH_FIELD_NUMBER: builtins.int
    MIN_VIA_ANNULAR_WIDTH_FIELD_NUMBER: builtins.int
    MIN_VIA_SIZE_FIELD_NUMBER: builtins.int
    MIN_THROUGH_DRILL_FIELD_NUMBER: builtins.int
    MIN_MICROVIA_SIZE_FIELD_NUMBER: builtins.int
    MIN_MICROVIA_DRILL_FIELD_NUMBER: builtins.int
    COPPER_EDGE_CLEARANCE_FIELD_NUMBER: builtins.int
    HOLE_CLEARANCE_FIELD_NUMBER: builtins.int
    HOLE_TO_HOLE_MIN_FIELD_NUMBER: builtins.int
    SILK_CLEARANCE_FIELD_NUMBER: builtins.int
    MIN_RESOLVED_SPOKES_FIELD_NUMBER: builtins.int
    MIN_SILK_TEXT_HEIGHT_FIELD_NUMBER: builtins.int
    MIN_SILK_TEXT_THICKNESS_FIELD_NUMBER: builtins.int
    min_resolved_spokes: builtins.int

    @property
    def min_clearance(self) -> common.types.base_types_pb2.Distance:
        ...

    @property
    def min_groove_width(self) -> common.types.base_types_pb2.Distance:
        ...

    @property
    def min_connection_width(self) -> common.types.base_types_pb2.Distance:
        ...

    @property
    def min_track_width(self) -> common.types.base_types_pb2.Distance:
        ...

    @property
    def min_via_annular_width(self) -> common.types.base_types_pb2.Distance:
        ...

    @property
    def min_via_size(self) -> common.types.base_types_pb2.Distance:
        ...

    @property
    def min_through_drill(self) -> common.types.base_types_pb2.Distance:
        ...

    @property
    def min_microvia_size(self) -> common.types.base_types_pb2.Distance:
        ...

    @property
    def min_microvia_drill(self) -> common.types.base_types_pb2.Distance:
        ...

    @property
    def copper_edge_clearance(self) -> common.types.base_types_pb2.Distance:
        ...

    @property
    def hole_clearance(self) -> common.types.base_types_pb2.Distance:
        ...

    @property
    def hole_to_hole_min(self) -> common.types.base_types_pb2.Distance:
        ...

    @property
    def silk_clearance(self) -> common.types.base_types_pb2.Distance:
        ...

    @property
    def min_silk_text_height(self) -> common.types.base_types_pb2.Distance:
        ...

    @property
    def min_silk_text_thickness(self) -> common.types.base_types_pb2.Distance:
        ...

    def __init__(self, *, min_clearance: common.types.base_types_pb2.Distance | None=..., min_groove_width: common.types.base_types_pb2.Distance | None=..., min_connection_width: common.types.base_types_pb2.Distance | None=..., min_track_width: common.types.base_types_pb2.Distance | None=..., min_via_annular_width: common.types.base_types_pb2.Distance | None=..., min_via_size: common.types.base_types_pb2.Distance | None=..., min_through_drill: common.types.base_types_pb2.Distance | None=..., min_microvia_size: common.types.base_types_pb2.Distance | None=..., min_microvia_drill: common.types.base_types_pb2.Distance | None=..., copper_edge_clearance: common.types.base_types_pb2.Distance | None=..., hole_clearance: common.types.base_types_pb2.Distance | None=..., hole_to_hole_min: common.types.base_types_pb2.Distance | None=..., silk_clearance: common.types.base_types_pb2.Distance | None=..., min_resolved_spokes: builtins.int=..., min_silk_text_height: common.types.base_types_pb2.Distance | None=..., min_silk_text_thickness: common.types.base_types_pb2.Distance | None=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['copper_edge_clearance', b'copper_edge_clearance', 'hole_clearance', b'hole_clearance', 'hole_to_hole_min', b'hole_to_hole_min', 'min_clearance', b'min_clearance', 'min_connection_width', b'min_connection_width', 'min_groove_width', b'min_groove_width', 'min_microvia_drill', b'min_microvia_drill', 'min_microvia_size', b'min_microvia_size', 'min_silk_text_height', b'min_silk_text_height', 'min_silk_text_thickness', b'min_silk_text_thickness', 'min_through_drill', b'min_through_drill', 'min_track_width', b'min_track_width', 'min_via_annular_width', b'min_via_annular_width', 'min_via_size', b'min_via_size', 'silk_clearance', b'silk_clearance']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['copper_edge_clearance', b'copper_edge_clearance', 'hole_clearance', b'hole_clearance', 'hole_to_hole_min', b'hole_to_hole_min', 'min_clearance', b'min_clearance', 'min_connection_width', b'min_connection_width', 'min_groove_width', b'min_groove_width', 'min_microvia_drill', b'min_microvia_drill', 'min_microvia_size', b'min_microvia_size', 'min_resolved_spokes', b'min_resolved_spokes', 'min_silk_text_height', b'min_silk_text_height', 'min_silk_text_thickness', b'min_silk_text_thickness', 'min_through_drill', b'min_through_drill', 'min_track_width', b'min_track_width', 'min_via_annular_width', b'min_via_annular_width', 'min_via_size', b'min_via_size', 'silk_clearance', b'silk_clearance']) -> None:
        ...
global___MinimumConstraints = MinimumConstraints

@typing.final
class PresetTrackWidth(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    WIDTH_FIELD_NUMBER: builtins.int

    @property
    def width(self) -> common.types.base_types_pb2.Distance:
        ...

    def __init__(self, *, width: common.types.base_types_pb2.Distance | None=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['width', b'width']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['width', b'width']) -> None:
        ...
global___PresetTrackWidth = PresetTrackWidth

@typing.final
class PresetViaDimension(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    DIAMETER_FIELD_NUMBER: builtins.int
    DRILL_FIELD_NUMBER: builtins.int

    @property
    def diameter(self) -> common.types.base_types_pb2.Distance:
        ...

    @property
    def drill(self) -> common.types.base_types_pb2.Distance:
        ...

    def __init__(self, *, diameter: common.types.base_types_pb2.Distance | None=..., drill: common.types.base_types_pb2.Distance | None=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['diameter', b'diameter', 'drill', b'drill']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['diameter', b'diameter', 'drill', b'drill']) -> None:
        ...
global___PresetViaDimension = PresetViaDimension

@typing.final
class PresetDiffPairDimension(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    WIDTH_FIELD_NUMBER: builtins.int
    GAP_FIELD_NUMBER: builtins.int
    VIA_GAP_FIELD_NUMBER: builtins.int

    @property
    def width(self) -> common.types.base_types_pb2.Distance:
        ...

    @property
    def gap(self) -> common.types.base_types_pb2.Distance:
        ...

    @property
    def via_gap(self) -> common.types.base_types_pb2.Distance:
        ...

    def __init__(self, *, width: common.types.base_types_pb2.Distance | None=..., gap: common.types.base_types_pb2.Distance | None=..., via_gap: common.types.base_types_pb2.Distance | None=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['gap', b'gap', 'via_gap', b'via_gap', 'width', b'width']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['gap', b'gap', 'via_gap', b'via_gap', 'width', b'width']) -> None:
        ...
global___PresetDiffPairDimension = PresetDiffPairDimension

@typing.final
class PredefinedSizes(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    TRACKS_FIELD_NUMBER: builtins.int
    VIAS_FIELD_NUMBER: builtins.int
    DIFF_PAIRS_FIELD_NUMBER: builtins.int

    @property
    def tracks(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___PresetTrackWidth]:
        ...

    @property
    def vias(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___PresetViaDimension]:
        ...

    @property
    def diff_pairs(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___PresetDiffPairDimension]:
        ...

    def __init__(self, *, tracks: collections.abc.Iterable[global___PresetTrackWidth] | None=..., vias: collections.abc.Iterable[global___PresetViaDimension] | None=..., diff_pairs: collections.abc.Iterable[global___PresetDiffPairDimension] | None=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['diff_pairs', b'diff_pairs', 'tracks', b'tracks', 'vias', b'vias']) -> None:
        ...
global___PredefinedSizes = PredefinedSizes

@typing.final
class SolderMaskPasteDefaults(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    MASK_EXPANSION_FIELD_NUMBER: builtins.int
    MASK_MIN_WIDTH_FIELD_NUMBER: builtins.int
    MASK_TO_COPPER_CLEARANCE_FIELD_NUMBER: builtins.int
    PASTE_MARGIN_FIELD_NUMBER: builtins.int
    PASTE_MARGIN_RATIO_FIELD_NUMBER: builtins.int
    ALLOW_SOLDERMASK_BRIDGES_IN_FOOTPRINTS_FIELD_NUMBER: builtins.int
    paste_margin_ratio: builtins.float
    allow_soldermask_bridges_in_footprints: builtins.bool

    @property
    def mask_expansion(self) -> common.types.base_types_pb2.Distance:
        ...

    @property
    def mask_min_width(self) -> common.types.base_types_pb2.Distance:
        ...

    @property
    def mask_to_copper_clearance(self) -> common.types.base_types_pb2.Distance:
        ...

    @property
    def paste_margin(self) -> common.types.base_types_pb2.Distance:
        ...

    def __init__(self, *, mask_expansion: common.types.base_types_pb2.Distance | None=..., mask_min_width: common.types.base_types_pb2.Distance | None=..., mask_to_copper_clearance: common.types.base_types_pb2.Distance | None=..., paste_margin: common.types.base_types_pb2.Distance | None=..., paste_margin_ratio: builtins.float=..., allow_soldermask_bridges_in_footprints: builtins.bool=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['mask_expansion', b'mask_expansion', 'mask_min_width', b'mask_min_width', 'mask_to_copper_clearance', b'mask_to_copper_clearance', 'paste_margin', b'paste_margin']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['allow_soldermask_bridges_in_footprints', b'allow_soldermask_bridges_in_footprints', 'mask_expansion', b'mask_expansion', 'mask_min_width', b'mask_min_width', 'mask_to_copper_clearance', b'mask_to_copper_clearance', 'paste_margin', b'paste_margin', 'paste_margin_ratio', b'paste_margin_ratio']) -> None:
        ...
global___SolderMaskPasteDefaults = SolderMaskPasteDefaults

@typing.final
class TeardropTargetParams(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ENABLED_FIELD_NUMBER: builtins.int
    MAX_LENGTH_FIELD_NUMBER: builtins.int
    MAX_WIDTH_FIELD_NUMBER: builtins.int
    BEST_LENGTH_RATIO_FIELD_NUMBER: builtins.int
    BEST_WIDTH_RATIO_FIELD_NUMBER: builtins.int
    WIDTH_TO_SIZE_FILTER_RATIO_FIELD_NUMBER: builtins.int
    CURVED_EDGES_FIELD_NUMBER: builtins.int
    ALLOW_TWO_TRACKS_FIELD_NUMBER: builtins.int
    ON_PADS_IN_ZONES_FIELD_NUMBER: builtins.int
    enabled: builtins.bool
    best_length_ratio: builtins.float
    best_width_ratio: builtins.float
    width_to_size_filter_ratio: builtins.float
    curved_edges: builtins.bool
    allow_two_tracks: builtins.bool
    on_pads_in_zones: builtins.bool

    @property
    def max_length(self) -> common.types.base_types_pb2.Distance:
        ...

    @property
    def max_width(self) -> common.types.base_types_pb2.Distance:
        ...

    def __init__(self, *, enabled: builtins.bool=..., max_length: common.types.base_types_pb2.Distance | None=..., max_width: common.types.base_types_pb2.Distance | None=..., best_length_ratio: builtins.float=..., best_width_ratio: builtins.float=..., width_to_size_filter_ratio: builtins.float=..., curved_edges: builtins.bool=..., allow_two_tracks: builtins.bool=..., on_pads_in_zones: builtins.bool=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['max_length', b'max_length', 'max_width', b'max_width']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['allow_two_tracks', b'allow_two_tracks', 'best_length_ratio', b'best_length_ratio', 'best_width_ratio', b'best_width_ratio', 'curved_edges', b'curved_edges', 'enabled', b'enabled', 'max_length', b'max_length', 'max_width', b'max_width', 'on_pads_in_zones', b'on_pads_in_zones', 'width_to_size_filter_ratio', b'width_to_size_filter_ratio']) -> None:
        ...
global___TeardropTargetParams = TeardropTargetParams

@typing.final
class TeardropTargetEntry(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    TARGET_FIELD_NUMBER: builtins.int
    PARAMS_FIELD_NUMBER: builtins.int
    target: global___TeardropTarget.ValueType

    @property
    def params(self) -> global___TeardropTargetParams:
        ...

    def __init__(self, *, target: global___TeardropTarget.ValueType=..., params: global___TeardropTargetParams | None=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['params', b'params']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['params', b'params', 'target', b'target']) -> None:
        ...
global___TeardropTargetEntry = TeardropTargetEntry

@typing.final
class TeardropDefaults(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    TARGET_VIAS_FIELD_NUMBER: builtins.int
    TARGET_PTH_PADS_FIELD_NUMBER: builtins.int
    TARGET_SMD_PADS_FIELD_NUMBER: builtins.int
    TARGET_TRACK_TO_TRACK_FIELD_NUMBER: builtins.int
    USE_ROUND_SHAPES_ONLY_FIELD_NUMBER: builtins.int
    TARGET_PARAMS_FIELD_NUMBER: builtins.int
    target_vias: builtins.bool
    target_pth_pads: builtins.bool
    target_smd_pads: builtins.bool
    target_track_to_track: builtins.bool
    use_round_shapes_only: builtins.bool

    @property
    def target_params(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___TeardropTargetEntry]:
        ...

    def __init__(self, *, target_vias: builtins.bool=..., target_pth_pads: builtins.bool=..., target_smd_pads: builtins.bool=..., target_track_to_track: builtins.bool=..., use_round_shapes_only: builtins.bool=..., target_params: collections.abc.Iterable[global___TeardropTargetEntry] | None=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['target_params', b'target_params', 'target_pth_pads', b'target_pth_pads', 'target_smd_pads', b'target_smd_pads', 'target_track_to_track', b'target_track_to_track', 'target_vias', b'target_vias', 'use_round_shapes_only', b'use_round_shapes_only']) -> None:
        ...
global___TeardropDefaults = TeardropDefaults

@typing.final
class ViaProtectionDefaults(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    TENT_FRONT_FIELD_NUMBER: builtins.int
    TENT_BACK_FIELD_NUMBER: builtins.int
    COVER_FRONT_FIELD_NUMBER: builtins.int
    COVER_BACK_FIELD_NUMBER: builtins.int
    PLUG_FRONT_FIELD_NUMBER: builtins.int
    PLUG_BACK_FIELD_NUMBER: builtins.int
    CAP_FIELD_NUMBER: builtins.int
    FILL_FIELD_NUMBER: builtins.int
    tent_front: builtins.bool
    tent_back: builtins.bool
    cover_front: builtins.bool
    cover_back: builtins.bool
    plug_front: builtins.bool
    plug_back: builtins.bool
    cap: builtins.bool
    fill: builtins.bool

    def __init__(self, *, tent_front: builtins.bool=..., tent_back: builtins.bool=..., cover_front: builtins.bool=..., cover_back: builtins.bool=..., plug_front: builtins.bool=..., plug_back: builtins.bool=..., cap: builtins.bool=..., fill: builtins.bool=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['cap', b'cap', 'cover_back', b'cover_back', 'cover_front', b'cover_front', 'fill', b'fill', 'plug_back', b'plug_back', 'plug_front', b'plug_front', 'tent_back', b'tent_back', 'tent_front', b'tent_front']) -> None:
        ...
global___ViaProtectionDefaults = ViaProtectionDefaults

@typing.final
class DrcSeveritySetting(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    RULE_TYPE_FIELD_NUMBER: builtins.int
    SEVERITY_FIELD_NUMBER: builtins.int
    rule_type: global___DrcErrorType.ValueType
    severity: common.types.base_types_pb2.RuleSeverity.ValueType

    def __init__(self, *, rule_type: global___DrcErrorType.ValueType=..., severity: common.types.base_types_pb2.RuleSeverity.ValueType=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['rule_type', b'rule_type', 'severity', b'severity']) -> None:
        ...
global___DrcSeveritySetting = DrcSeveritySetting

@typing.final
class DrcExclusion(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    MARKER_FIELD_NUMBER: builtins.int
    COMMENT_FIELD_NUMBER: builtins.int
    comment: builtins.str

    @property
    def marker(self) -> common.types.base_types_pb2.RuleCheckerMarker:
        ...

    def __init__(self, *, marker: common.types.base_types_pb2.RuleCheckerMarker | None=..., comment: builtins.str=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['marker', b'marker']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['comment', b'comment', 'marker', b'marker']) -> None:
        ...
global___DrcExclusion = DrcExclusion

@typing.final
class CustomRuleDisallowSettings(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    TYPES_FIELD_NUMBER: builtins.int

    @property
    def types(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[global___CustomRuleDisallowType.ValueType]:
        ...

    def __init__(self, *, types: collections.abc.Iterable[global___CustomRuleDisallowType.ValueType] | None=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['types', b'types']) -> None:
        ...
global___CustomRuleDisallowSettings = CustomRuleDisallowSettings

@typing.final
class CustomRuleConstraint(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    TYPE_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    NUMERIC_FIELD_NUMBER: builtins.int
    DISALLOW_FIELD_NUMBER: builtins.int
    ZONE_CONNECTION_FIELD_NUMBER: builtins.int
    ASSERTION_EXPRESSION_FIELD_NUMBER: builtins.int
    OPTIONS_FIELD_NUMBER: builtins.int
    type: global___CustomRuleConstraintType.ValueType
    name: builtins.str
    zone_connection: board.board_types_pb2.ZoneConnectionStyle.ValueType
    assertion_expression: builtins.str

    @property
    def numeric(self) -> common.types.base_types_pb2.MinOptMax:
        """nanometers, picoseconds, or unitless depending on constraint type"""

    @property
    def disallow(self) -> global___CustomRuleDisallowSettings:
        ...

    @property
    def options(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[global___CustomRuleConstraintOption.ValueType]:
        """grab bag of stuff; may be refactored to more specific messages later"""

    def __init__(self, *, type: global___CustomRuleConstraintType.ValueType=..., name: builtins.str | None=..., numeric: common.types.base_types_pb2.MinOptMax | None=..., disallow: global___CustomRuleDisallowSettings | None=..., zone_connection: board.board_types_pb2.ZoneConnectionStyle.ValueType=..., assertion_expression: builtins.str=..., options: collections.abc.Iterable[global___CustomRuleConstraintOption.ValueType] | None=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['_name', b'_name', 'assertion_expression', b'assertion_expression', 'disallow', b'disallow', 'name', b'name', 'numeric', b'numeric', 'value', b'value', 'zone_connection', b'zone_connection']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['_name', b'_name', 'assertion_expression', b'assertion_expression', 'disallow', b'disallow', 'name', b'name', 'numeric', b'numeric', 'options', b'options', 'type', b'type', 'value', b'value', 'zone_connection', b'zone_connection']) -> None:
        ...

    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal['_name', b'_name']) -> typing.Literal['name'] | None:
        ...

    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal['value', b'value']) -> typing.Literal['numeric', 'disallow', 'zone_connection', 'assertion_expression'] | None:
        ...
global___CustomRuleConstraint = CustomRuleConstraint

@typing.final
class CustomRule(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    CONDITION_FIELD_NUMBER: builtins.int
    CONSTRAINTS_FIELD_NUMBER: builtins.int
    SINGLE_LAYER_FIELD_NUMBER: builtins.int
    LAYER_MODE_FIELD_NUMBER: builtins.int
    SEVERITY_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    COMMENTS_FIELD_NUMBER: builtins.int
    condition: builtins.str
    single_layer: board.board_types_pb2.BoardLayer.ValueType
    layer_mode: global___CustomRuleLayerMode.ValueType
    severity: common.types.base_types_pb2.RuleSeverity.ValueType
    name: builtins.str
    comments: builtins.str

    @property
    def constraints(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___CustomRuleConstraint]:
        ...

    def __init__(self, *, condition: builtins.str=..., constraints: collections.abc.Iterable[global___CustomRuleConstraint] | None=..., single_layer: board.board_types_pb2.BoardLayer.ValueType=..., layer_mode: global___CustomRuleLayerMode.ValueType=..., severity: common.types.base_types_pb2.RuleSeverity.ValueType=..., name: builtins.str=..., comments: builtins.str | None=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['_comments', b'_comments', 'comments', b'comments', 'layer_condition', b'layer_condition', 'layer_mode', b'layer_mode', 'single_layer', b'single_layer']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['_comments', b'_comments', 'comments', b'comments', 'condition', b'condition', 'constraints', b'constraints', 'layer_condition', b'layer_condition', 'layer_mode', b'layer_mode', 'name', b'name', 'severity', b'severity', 'single_layer', b'single_layer']) -> None:
        ...

    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal['_comments', b'_comments']) -> typing.Literal['comments'] | None:
        ...

    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal['layer_condition', b'layer_condition']) -> typing.Literal['single_layer', 'layer_mode'] | None:
        ...
global___CustomRule = CustomRule

@typing.final
class BoardDesignRules(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    CONSTRAINTS_FIELD_NUMBER: builtins.int
    PREDEFINED_SIZES_FIELD_NUMBER: builtins.int
    SOLDER_MASK_PASTE_FIELD_NUMBER: builtins.int
    TEARDROPS_FIELD_NUMBER: builtins.int
    VIA_PROTECTION_FIELD_NUMBER: builtins.int
    SEVERITIES_FIELD_NUMBER: builtins.int
    EXCLUSIONS_FIELD_NUMBER: builtins.int

    @property
    def constraints(self) -> global___MinimumConstraints:
        ...

    @property
    def predefined_sizes(self) -> global___PredefinedSizes:
        ...

    @property
    def solder_mask_paste(self) -> global___SolderMaskPasteDefaults:
        ...

    @property
    def teardrops(self) -> global___TeardropDefaults:
        ...

    @property
    def via_protection(self) -> global___ViaProtectionDefaults:
        ...

    @property
    def severities(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___DrcSeveritySetting]:
        ...

    @property
    def exclusions(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___DrcExclusion]:
        ...

    def __init__(self, *, constraints: global___MinimumConstraints | None=..., predefined_sizes: global___PredefinedSizes | None=..., solder_mask_paste: global___SolderMaskPasteDefaults | None=..., teardrops: global___TeardropDefaults | None=..., via_protection: global___ViaProtectionDefaults | None=..., severities: collections.abc.Iterable[global___DrcSeveritySetting] | None=..., exclusions: collections.abc.Iterable[global___DrcExclusion] | None=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['constraints', b'constraints', 'predefined_sizes', b'predefined_sizes', 'solder_mask_paste', b'solder_mask_paste', 'teardrops', b'teardrops', 'via_protection', b'via_protection']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['constraints', b'constraints', 'exclusions', b'exclusions', 'predefined_sizes', b'predefined_sizes', 'severities', b'severities', 'solder_mask_paste', b'solder_mask_paste', 'teardrops', b'teardrops', 'via_protection', b'via_protection']) -> None:
        ...
global___BoardDesignRules = BoardDesignRules